

// Google Maps JavaScript API key (client-side web key)




const LOC_BY_SLOT=Object.fromEntries(LOC_MEMBERS.map(x=>[x.slot,x]));

// font size controls
function applyFontSize(px){px=Math.max(17,Math.min(25,px));document.documentElement.style.setProperty('--fs',px+'px');localStorage.setItem('cro_font_size',String(px))}
function fontStep(d){let now=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--fs'))||19;applyFontSize(now+d)}
function fontReset(){applyFontSize(19)}
applyFontSize(+(localStorage.getItem('cro_font_size')||19));

function localDate(){let f=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zagreb',year:'numeric',month:'2-digit',day:'2-digit'});return f.format(new Date())}


function _normPlaceText(s){return String(s||'').toLowerCase().replace(/[^0-9a-z가-힣]+/g,' ').trim()}
function _placeTokens(s){let stop=new Set(['두브로브니크','스플리트','트로기르','자다르','자그레브','로마','핵심','관광','구시가지','코스','전체','성','the','old','town']);return _normPlaceText(s).split(/\s+/).filter(t=>t.length>1&&!stop.has(t))}
function _matchedAttractions(anchor,name){let city=document.querySelector(anchor);if(!city)return[];let q=_placeTokens(name),items=[...city.querySelectorAll('.attraction')];if(!q.length)return[];let scored=items.map(el=>{let title=el.querySelector('h4')?.textContent||'',nt=_placeTokens(title),score=q.reduce((s,t)=>s+(nt.some(n=>n.includes(t)||t.includes(n))?1:0),0);return {el,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);let best=scored[0]?.score||0;return scored.filter(x=>x.score>=Math.max(1,best-1)).slice(0,2).map(x=>x.el)}
function _inlineAttractionDetail(x){let city=document.querySelector(x.a),overview=city?.querySelector('.city-overview')?.textContent?.trim()||'',history=city?.querySelector('.read-more>p')?.textContent?.trim()||'',matches=_matchedAttractions(x.a,x.n),matchedHtml=matches.map(el=>el.outerHTML).join('');let route=city?.querySelector('.city-route-tip')?.outerHTML||'';return `<details class="inline-attraction-detail" ontoggle="singleOpenDetail(this)"><summary>상세보기</summary><div class="inline-detail-body">${overview?`<h5>📖 이 장소를 이해하기 위한 도시 배경</h5><div class="inline-city-context">${overview}</div>`:''}${history?`<div class="inline-history"><b>역사 한눈에</b><br>${history}</div>`:''}${matchedHtml||`<div class="inline-fallback"><b>${x.n}</b><br>${x.p}<br><br><b>꼭 볼 것</b><br>${x.m}<br><br><b>관람시간</b> ${x.t}<br><b>입장·요금</b> ${x.price}</div>`}${route}<button type="button" class="inline-close" onclick="closeInlineDetail(this)">▲ 상세 닫기</button></div></details>`}
function singleOpenDetail(el){if(!el.open)return;let grid=el.closest('.day-attraction-grid');if(!grid)return;grid.querySelectorAll('.inline-attraction-detail[open]').forEach(d=>{if(d!==el)d.open=false})}
function closeInlineDetail(btn){let det=btn.closest('.inline-attraction-detail'),card=btn.closest('.day-attraction-card');if(det)det.open=false;if(card)requestAnimationFrame(()=>card.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function dayAttractionHtml(d){let arr=DAY_ATTRACTIONS[d.date]||[];if(!arr.length)return'';return `<h3 class="day-attraction-title">관광지 가이드</h3><div class="day-attraction-grid">${arr.map(x=>`<article class="day-attraction-card"><h4>${x.n}</h4><p>${x.p}</p><div class="spot-meta"><span>⏱ ${x.t}</span><span>🎟 ${x.price}</span></div><div class="must-see"><b>무엇을 봐야 하나</b><br>${x.m}</div>${_inlineAttractionDetail(x)}<div class="btns"><a class="btn" target="_blank" rel="noopener" href="${x.book}">${x.book.includes('google.com/maps')?'📍 지도':'🎟 예매/공식'}</a></div></article>`).join('')}</div>`}
function expectedHourlyHtml(d){let w=WEATHER_SPOTS[d.date];if(!w)return'<div class="note">해당 날짜 기상 기준점이 없습니다.</div>';let vals=[['08:00',w.lo+2],['11:00',Math.round((w.lo+w.hi)/2)],['14:00',w.hi],['17:00',w.hi-2],['20:00',Math.max(w.lo+2,w.hi-5)]];return `<div class="day-weather-head"><b>${w.name} · 시간대별 장기 참고</b><small>실제 시간예보는 약 16일 전부터 자동 전환</small></div><div class="day-hourly">${vals.map(v=>`<div class="day-hour"><div class="t">${v[0]}</div><div class="i">🌤️</div><div class="temp">약 ${v[1]}°</div><div class="sub">평년 참고<br>강수확률 미제공</div></div>`).join('')}</div>`}
async function loadDayWeather(i){let d=days[i],box=document.getElementById(`dayWeather-${i}`);if(!box)return;let w=WEATHER_SPOTS[d.date];if(!w){box.innerHTML='<div class="note">날씨 정보가 없습니다.</div>';return}let diff=daysDiff(d.date,croDate());if(diff>15||diff<0){box.innerHTML=expectedHourlyHtml(d);return}box.innerHTML='<div class="small muted">시간대별 예보 불러오는 중…</div>';try{let url=`https://api.open-meteo.com/v1/forecast?latitude=${w.lat}&longitude=${w.lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m&timezone=Europe%2FZagreb&start_date=${d.date}&end_date=${d.date}`;let j=await tinyFetch(url),times=j.hourly?.time||[],temps=j.hourly?.temperature_2m||[],feel=j.hourly?.apparent_temperature||[],rain=j.hourly?.precipitation_probability||[],codes=j.hourly?.weather_code||[],wind=j.hourly?.wind_speed_10m||[],hours=['08','11','14','17','20'],idx=hours.map(h=>times.findIndex(t=>t.slice(11,13)===h)).filter(x=>x>=0);box.innerHTML=`<div class="day-weather-head"><b>${w.name} · ${d.date.slice(5).replace('-','/')} 시간대별 예보</b><small>${fmtFetchTime()} 갱신</small></div><div class="day-hourly">${idx.map(k=>`<div class="day-hour"><div class="t">${times[k].slice(11,16)}</div><div class="i">${weatherIcon(codes[k])}</div><div class="temp">${Math.round(temps[k])}°</div><div class="sub">체감 ${Math.round(feel[k]??temps[k])}°<br>비 ${rain[k]??0}% · 바람 ${Math.round(wind[k]??0)}km/h</div></div>`).join('')}</div>`}catch(e){box.innerHTML=expectedHourlyHtml(d)}}
function hotelForDate(date){return window.CRO_HOTEL_BY_DATE?.[date]||null}
function escHotel(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dayHotelHtml(date){
  const h=hotelForDate(date); if(!h)return'';
  return `<div class="day-hotel-card card"><div class="day-hotel-head"><small>TONIGHT</small><span class="stay-badge">${escHotel(h.stayEn||h.stay)}</span></div><h4>${escHotel(h.name)}</h4><p><b>ADDRESS</b> · ${escHotel(h.address)}<br><b>PHONE</b> · ${escHotel(h.phone)}</p><div class="day-hotel-actions"><a href="tel:${escHotel(h.tel)}">☎ 전화</a><a href="${escHotel(h.map)}" target="_blank" rel="noopener">📍 지도</a><a href="#hotels">호텔 상세</a></div></div>`;
}
function renderHotelImmigration(){
  const box=document.getElementById('hotelImmigrationCard'); if(!box||!Array.isArray(window.CRO_HOTELS))return;
  box.innerHTML=`<div class="hotel-immigration-head"><b>ACCOMMODATION</b><small>입국심사 시 바로 보여줄 숙소 정보</small></div><div class="hotel-immigration-list">${window.CRO_HOTELS.map(h=>`<div class="hotel-immigration-row"><div class="stay">STAY · ${escHotel(h.stay)}</div><strong>${escHotel(h.name)}</strong><address>${escHotel(h.address)}</address><a href="tel:${escHotel(h.tel)}">TEL ${escHotel(h.phone)}</a></div>`).join('')}</div>`;
}
function renderHotels(){
  const box=document.getElementById('hotelDirectory'); if(!box||!Array.isArray(window.CRO_HOTELS))return;
  box.innerHTML=window.CRO_HOTELS.map(h=>`<article class="hotel-detail-card card" id="hotel-${escHotel(h.id)}"><div class="hotel-photo-wrap"><img src="${escHotel(h.image)}" alt="${escHotel(h.name)}" loading="lazy" decoding="async" onerror="this.style.display='none';this.nextElementSibling.style.zIndex='0'"><div class="hotel-photo-fallback">${escHotel(h.name)}</div></div><div class="hotel-detail-body"><span class="hotel-stay-line">STAY · ${escHotel(h.stayEn||h.stay)}</span><h3>${escHotel(h.name)}</h3><dl class="hotel-essential"><div><dt>STAY</dt><dd>${escHotel(h.stayEn||h.stay)}</dd></div><div><dt>ADDRESS</dt><dd>${escHotel(h.address)}</dd></div><div><dt>PHONE</dt><dd><a href="tel:${escHotel(h.tel)}">${escHotel(h.phone)}</a>${h.secondaryPhone?`<br><small>RESERVATIONS · ${escHotel(h.secondaryPhone.replace(/^예약\/세일즈\s*/,'').replace(/^콜센터\s*/,''))}</small>`:''}</dd></div><div><dt>EMAIL</dt><dd>${escHotel(h.email)}</dd></div></dl><p class="hotel-blurb">${escHotel(h.blurb)}</p><div class="hotel-highlights">${(h.highlights||[]).map(x=>`<span>${escHotel(x)}</span>`).join('')}</div><div class="hotel-buttons"><a class="primary" href="tel:${escHotel(h.tel)}">☎ 전화</a><a href="${escHotel(h.map)}" target="_blank" rel="noopener">📍 지도</a><a href="${escHotel(h.website)}" target="_blank" rel="noopener">공식 사이트</a></div></div></article>`).join('');
}
function renderDays(){
  let tabs=document.getElementById('dayTabs'),wrap=document.getElementById('dayPanels');tabs.innerHTML='';wrap.innerHTML='';
  days.forEach((d,i)=>{
    let b=document.createElement('button');b.className='tab';b.textContent=d.date.slice(5).replace('-','/');b.onclick=()=>selectDay(i);tabs.appendChild(b);
    let p=document.createElement('div');p.className='panel';
    let flow=(d.flow||[]).map((x,j)=>`<span class="flow-stop"><span class="flow-pill"><i aria-hidden="true">${j+1}</i><span>${x}</span></span></span>`).join('');
    let moves=(d.moves||[]).map(m=>`<div class="move-row"><span class="move-mode">${m[0]}</span><span class="move-route">${m[1]}</span><span class="move-time">${m[2]}</span></div>`).join('');
    let gl=(d.guides||[]).map(g=>`<a href="${g[1]}">📖 ${g[0]} 상세가이드</a>`).join('');
    p.innerHTML=`${dayHotelHtml(d.date)}<div class="day-summary"><h3>${d.title}</h3><p><b>이동동선</b> ${d.route}</p><div class="day-flow">${flow}</div><div class="day-guide-links">${gl}</div>${d.map?`<div class="btns"><a class="btn" target="_blank" rel="noopener" href="${d.map}">📍 Google 전체 동선</a></div>`:''}</div><div class="day-weather-box" id="dayWeather-${i}">${expectedHourlyHtml(d)}</div><div class="day-main-grid"><div class="card"><h3>일정</h3><div class="timeline">${d.events.map(e=>`<div class="event"><span class="time">${e[0]}</span>${e[1]}</div>`).join('')}</div>${d.meal?`<div class="meal"><b>식사</b><br>${d.meal}</div>`:''}</div><div class="card"><h3>구간별 이동시간</h3><div class="move-list">${moves}</div></div></div>${dayAttractionHtml(d)}`;
    wrap.appendChild(p)
  });
  let idx=days.findIndex(x=>x.date===localDate());selectDay(idx>=0?idx:0);
}
function selectDay(i){document.querySelectorAll('.tab').forEach((x,j)=>x.classList.toggle('active',i===j));document.querySelectorAll('.panel').forEach((x,j)=>x.classList.toggle('active',i===j));loadDayWeather(i);let p=document.querySelectorAll('.panel')[i];if(p&&location.hash==='#schedule')setTimeout(()=>p.scrollIntoView({behavior:'smooth',block:'start'}),40)}
// weather / fx lightweight
let autoBytes=0;
function addAuto(n){autoBytes+=n;let el=document.getElementById('liveData');if(el)el.textContent='🌐 자동데이터 '+(autoBytes/1024).toFixed(1)+' KB'}
async function tinyFetch(url){let h=0;for(let i=0;i<url.length;i++)h=((h<<5)-h+url.charCodeAt(i))|0;let k='cro.http.'+Math.abs(h),now=Date.now(),saved=null;try{saved=JSON.parse(localStorage.getItem(k)||'null')}catch(_){}if(saved&&now-(saved.at||0)<3600000)return saved.data;if(navigator.onLine===false){if(saved?.data)return saved.data;let e=Error('오프라인 · 실시간 데이터 연결 필요');e.code='OFFLINE';throw e}try{let r=await fetch(url,{cache:'default'}),tx=await r.text();addAuto(tx.length);if(!r.ok)throw Error(r.status);let data=JSON.parse(tx);try{localStorage.setItem(k,JSON.stringify({at:now,data}))}catch(_){}return data}catch(e){if(saved?.data)return saved.data;throw e}}

function croDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zagreb',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function weatherTarget(){let d=croDate();if(WEATHER_SPOTS[d])return {date:d,...WEATHER_SPOTS[d]};if(d<'2026-10-12')return {date:'2026-10-13',...WEATHER_SPOTS['2026-10-13']};return {date:'2026-10-18',...WEATHER_SPOTS['2026-10-18']}}
function weatherIcon(code){if(code===0)return'☀️';if([1,2].includes(code))return'🌤️';if(code===3)return'☁️';if([45,48].includes(code))return'🌫️';if([51,53,55,61,63,65,80,81,82].includes(code))return'🌧️';if([71,73,75,77,85,86].includes(code))return'🌨️';if([95,96,99].includes(code))return'⛈️';return'🌤️'}
function daysDiff(a,b){return Math.round((new Date(a+'T00:00:00Z')-new Date(b+'T00:00:00Z'))/86400000)}
function fmtFetchTime(){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Europe/Zagreb',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date())}
function renderExpectedOutlook(){let box=document.getElementById('tripWeatherOutlook');if(!box)return;box.innerHTML=Object.entries(WEATHER_SPOTS).map(([d,w])=>`<div class="outlook-item"><b>${d.slice(5).replace('-','/')} ${w.name}</b>예상 ${w.hi}° / ${w.lo}°</div>`).join('')}
function renderHourlyWeather(w,target){let box=document.getElementById('hourlyWeather');if(!box)return;let times=w.hourly?.time||[],temps=w.hourly?.temperature_2m||[],feels=w.hourly?.apparent_temperature||[],rain=w.hourly?.precipitation_probability||[],codes=w.hourly?.weather_code||[],wind=w.hourly?.wind_speed_10m||[];let nowHour=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Zagreb',hour:'2-digit',hour12:false}).format(new Date());let keep=[];for(let i=0;i<times.length;i++){let t=times[i],h=t.slice(11,13);if(target.date===croDate()){if(+h < Math.max(0,+nowHour-1))continue;if(keep.length>=12)break}else{if(+h<7||+h>21||(+h%2))continue;if(keep.length>=8)break}keep.push(i)}box.innerHTML=keep.map(i=>{let h=times[i].slice(11,16),isNow=target.date===croDate()&&times[i].slice(11,13)===String(nowHour).padStart(2,'0');return `<div class="hourly-item ${isNow?'now':''}"><div class="hourly-time">${h}</div><div class="hourly-icon">${weatherIcon(codes[i])}</div><div class="hourly-temp">${Math.round(temps[i])}°</div><div class="hourly-rain">비 ${rain[i]??0}% · ${Math.round(wind[i]??0)}km/h</div><div class="hourly-rain">체감 ${Math.round(feels[i]??temps[i])}°</div></div>`}).join('')}
async function refreshWeather(){let t=weatherTarget(),today=croDate(),diff=daysDiff(t.date,today),main=document.getElementById('liveWeatherMain'),upd=document.getElementById('weatherUpdated'),title=document.getElementById('weatherDetailTitle'),big=document.getElementById('weatherBigTemp'),meta=document.getElementById('weatherDetailMeta');renderExpectedOutlook();if(diff>15||diff<0){main.textContent=`🌤️ ${t.date.slice(5).replace('-','/')} ${t.name} 예상 ${t.hi}/${t.lo}°`;upd.textContent='장기 참고값 · 상세보기';title.textContent=`${t.name} · 여행 예상날씨`;big.textContent=`${t.hi}°`;meta.textContent=`최고 ${t.hi}° · 최저 ${t.lo}° · 상세 실시간 예보는 약 16일 전부터 자동 표시됩니다.`;document.getElementById('hourlyWeather').innerHTML='<div class="note" style="min-width:100%">현재는 장기예보 범위 밖입니다. 여행이 가까워지면 이 영역이 해당 날짜의 시간대별 기온·강수확률·바람으로 자동 전환됩니다.</div>';return}try{let url=`https://api.open-meteo.com/v1/forecast?latitude=${t.lat}&longitude=${t.lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code&timezone=Europe%2FZagreb&start_date=${t.date}&end_date=${t.date}`;let w=await tinyFetch(url),hi=Math.round(w.daily.temperature_2m_max[0]),lo=Math.round(w.daily.temperature_2m_min[0]),rain=w.daily.precipitation_probability_max?.[0]??0,code=w.daily.weather_code?.[0]??1,firstTemp=w.hourly?.temperature_2m?.[0];main.textContent=`${weatherIcon(code)} ${t.name} ${hi}/${lo}° · 비 ${rain}%`;upd.textContent=fmtFetchTime()+' 갱신 · 상세보기';title.textContent=`${t.date.slice(5).replace('-','/')} ${t.name} 시간대별 예보`;big.textContent=(firstTemp!=null?Math.round(firstTemp):hi)+'°';meta.textContent=`최고 ${hi}° · 최저 ${lo}° · 최대 강수확률 ${rain}% · ${fmtFetchTime()} 갱신`;renderHourlyWeather(w,t);}catch(e){main.textContent=`🌤️ ${t.name} 예상 ${t.hi}/${t.lo}°`;upd.textContent=(navigator.onLine===false?'오프라인 · 참고값':'예보 연결 실패 · 참고값');title.textContent=t.name+' 예상날씨';big.textContent=t.hi+'°';meta.textContent=(navigator.onLine===false?'인터넷 연결이 없어 저장·참고값을 표시합니다. · ':'')+`예상 최고 ${t.hi}° · 최저 ${t.lo}°`;}}
renderDays();
renderHotels();
// FX retrieval is owned by fx-service.js; do not hide errors with a fixed rate.
let currentEurKrw=null;
function updateGuidePrices(rate){
  const valid=typeof rate==='number'&&Number.isFinite(rate)&&rate>0;
  currentEurKrw=valid?rate:null;
  document.querySelectorAll('.eur-price').forEach(el=>{
    const eur=Number(el.dataset.eur);if(!Number.isFinite(eur))return;
    el.textContent=valid?'≈ ₩'+(Math.round(eur*rate/100)*100).toLocaleString('ko-KR'):'원화 환산 대기';
  });
}
async function refreshFx(force=false){return window.FxService?.refresh(force);}
async function refreshLive(){return Promise.allSettled([refreshWeather(),refreshFx()]);}
refreshWeather();
setInterval(()=>{if(!document.hidden)refreshWeather()},3600000);

// ===== login + location + attendance =====
const LIVE5=5*60*1000, RECENT15=15*60*1000, RECENT30=30*60*1000, HOUR1=60*60*1000, HOUR3=3*60*60*1000, HOUR6=6*60*60*1000, SHOWMAX=24*60*60*1000;
const APP_USERS=TEAM_MEMBERS.map(u=>{let lm=LOC_MEMBERS.find(x=>x.name===u.name);return {...u,slot:u.group===0?'prof1':(lm?.slot||''),groupLabel:u.group===0?'교수님':`${u.group}조`}});
const APP_BY_SLOT=Object.fromEntries(APP_USERS.map(u=>[u.slot,u]));
let currentUser=null,locCache={},locTimer=null,pollTimer=null,mapObj=null,markers=[],historyLayer=null,locBytes=0,locLastPos=null,locLastWrite=+(localStorage.getItem('loc_lastwrite')||0),locFilter='all';
let attCurrent=null,attChecks={},attTimer=null,attFilter='all';
function esc(x){return String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function userByName(n){return APP_USERS.find(u=>u.name===String(n||'').trim())}
function userGroupText(u){return u?.group===0?'교수님':`${u?.group||'-'}조${u?.leader?' · 조장':''}${u?.tripRole?' · '+u.tripRole:''}`}
// MIX05: remember only a successful local identity; enter after an explicit tap.
const LOGIN_MEMORY_KEY='cro.login.identity.v5';
let rememberedLogin=null;
function rememberedAccount(){
  try{
    const name=localStorage.getItem('cro_login_name')||'',u=userByName(name);
    if(!u)return null;
    const saved=JSON.parse(localStorage.getItem(LOGIN_MEMORY_KEY)||'null');
    if(saved && (saved.name!==u.name || saved.memberId!==u.memberId))return null;
    return u;
  }catch(_){return null}
}
function paintLoginGate(){
  const known=!!rememberedLogin;
  document.querySelectorAll('#loginScreen .login-field').forEach(e=>e.hidden=known);
  const card=document.getElementById('rememberedLoginCard');
  if(card){card.hidden=!known;document.getElementById('rememberedLoginName').textContent=known?rememberedLogin.name+'\ub2d8':'';document.getElementById('rememberedLoginRole').textContent=known?userGroupText(rememberedLogin):'';}
  document.getElementById('loginSubmit').textContent=known?rememberedLogin.name+'\ub2d8\uc73c\ub85c \ub85c\uadf8\uc778':'\ub85c\uadf8\uc778';
  document.getElementById('loginSwitch').hidden=!known;
  document.getElementById('loginName').value=known?rememberedLogin.name:'';
  document.getElementById('loginPass').value='';
  document.getElementById('loginError').textContent='';
}
function appInitLogin(){
  document.body.classList.remove('login-ready');currentUser=null;
  rememberedLogin=rememberedAccount();paintLoginGate();
  document.getElementById('loginScreen').classList.remove('hidden');
}
function appUseAnotherAccount(){
  if(currentUser){appLogout();return}
  ['cro_login_name','cro_login_pass',LOGIN_MEMORY_KEY].forEach(k=>localStorage.removeItem(k));
  rememberedLogin=null;paintLoginGate();
}
function appLogin(){
  const err=document.getElementById('loginError');let u;
  if(rememberedLogin){
    u=rememberedAccount();
    if(!u||u.memberId!==rememberedLogin.memberId){rememberedLogin=null;paintLoginGate();err.textContent='\uc800\uc7a5\ub41c \uacc4\uc815\uc744 \ub2e4\uc2dc \ud655\uc778\ud574 \uc8fc\uc138\uc694.';return;}
  }else{
    const name=(document.getElementById('loginName').value||'').replace(/\s+/g,''),pass=(document.getElementById('loginPass').value||'').trim();
    document.getElementById('loginName').value=name;u=userByName(name);
    if(!u||!/^\d{4}$/.test(pass)||pass!==u.phone.replace(/\D/g,'').slice(-4)){err.textContent='\uc774\ub984\uacfc \ud734\ub300\uc804\ud654 \ub05d 4\uc790\ub9ac\ub97c \ud655\uc778\ud574 \uc8fc\uc138\uc694.';return;}
  }
  currentUser=u;
  try{localStorage.setItem('cro_login_name',u.name);localStorage.setItem(LOGIN_MEMORY_KEY,JSON.stringify({name:u.name,memberId:u.memberId}));localStorage.removeItem('cro_login_pass');}catch(_){}
  localStorage.setItem('loc_slot',u.slot);localStorage.setItem('loc_name',u.name);
  rememberedLogin=u;document.getElementById('loginPass').value='';err.textContent='';appEnter();
}
function appEnter(){document.body.classList.add('spa-mode','login-ready');document.getElementById('loginScreen').classList.add('hidden');let chip=document.getElementById('loginUserChip');chip.innerHTML=`👤 ${esc(currentUser.name)}<small>${userGroupText(currentUser)}</small>`;document.getElementById('accountName').textContent=currentUser.name;document.getElementById('accountMeta').textContent=`${userGroupText(currentUser)} · ${currentUser.org} · ${currentUser.title}`;let id=document.getElementById('locMyIdentity'),meta=document.getElementById('locMyIdentityMeta');if(id)id.textContent=`${currentUser.name} · ${userGroupText(currentUser)}`;if(meta)meta.textContent=`${currentUser.org} · ${currentUser.title} · 위치 DB 이름: ${currentUser.name}`;let admin=currentUser.name==='한상호';document.getElementById('attAdmin')?.classList.toggle('show',admin);let locReset=document.getElementById('locAdminResetWrap');if(locReset)locReset.hidden=!admin;localStorage.setItem('loc_slot',currentUser.slot);window.dispatchEvent(new CustomEvent('cro-auth-change'));locRefreshAll(false);attRefresh(false)}
async function appLogout(){try{if(localStorage.getItem('loc_sharing')==='1')await locStopSharing()}catch(e){}localStorage.removeItem('cro_login_name');localStorage.removeItem('cro_login_pass');localStorage.removeItem(LOGIN_MEMORY_KEY);rememberedLogin=null;paintLoginGate();document.body.classList.remove('login-ready');currentUser=null;window.dispatchEvent(new CustomEvent('cro-auth-change'));document.getElementById('accountPop').classList.remove('show');document.getElementById('loginPass').value='';document.getElementById('loginScreen').classList.remove('hidden')}
function toggleAccountPop(){document.getElementById('accountPop').classList.toggle('show')}
function ago(ts){if(!ts)return '-';let m=Math.floor((Date.now()-ts)/60000);if(m<1)return '방금';if(m<60)return `${m}분 전`;let h=Math.floor(m/60);if(h<24)return `${h}시간 ${m%60}분 전`;return `${Math.floor(h/24)}일 전`}
function lastSeenClock(ts){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Europe/Zagreb',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
const LOC_GROUP_COLORS={0:'#34495e',1:'#2274c9',2:'#26a269',3:'#e3912e',4:'#8a5bb7'};
function locGroupColor(g){return LOC_GROUP_COLORS[g]||'#607d8b'}
function locAgeInfo(ts){if(!ts)return {cls:'age-off',color:'#c6cdd1',label:'미공유'};let a=Date.now()-ts;if(a<=LIVE5)return {cls:'age-live',color:'#25a66a',label:'실시간'};if(a<=RECENT15)return {cls:'age-recent',color:'#2784c7',label:'5~15분'};if(a<=RECENT30)return {cls:'age-warn',color:'#e29a37',label:'15~30분'};if(a<=HOUR1)return {cls:'age-late',color:'#d85f52',label:'30~60분'};if(a<=HOUR3)return {cls:'age-1h',color:'#8156a5',label:'1~3시간'};return {cls:'age-old',color:'#8b969d',label:a<=HOUR6?'3~6시간':'6시간+'}}
function locCount(n){locBytes+=Math.max(0,n||0);let el=document.getElementById('locDataUsage');if(el)el.textContent=`이번 세션 위치 데이터 약 ${(locBytes/1024).toFixed(1)} KB · 실제 통신량은 HTTP/TLS 포함 시 더 큼`}
function updateLiveLocChip(){let el=document.getElementById('liveLoc');if(!el)return;let on=localStorage.getItem('loc_sharing')==='1',ts=locLastWrite||+(localStorage.getItem('loc_lastwrite')||0)||(currentUser&&locCache[currentUser.slot]?.ts)||0;el.classList.remove('transmitting','delayed');if(!on){el.textContent='📍 내 위치 OFF';return}if(ts&&Date.now()-ts<=LIVE5){el.classList.add('transmitting');el.textContent='📍 위치 전송중 · '+ago(ts)}else if(ts){el.classList.add('delayed');el.textContent='⚠ 위치공유 ON · '+ago(ts)}else{el.classList.add('delayed');el.textContent='⏳ 위치 전송 준비중'}}
async function token(){let tok=localStorage.getItem('fb_tok'),exp=+(localStorage.getItem('fb_exp')||0);if(tok&&Date.now()<exp)return tok;let rf=localStorage.getItem('fb_rf');if(rf){let b=new URLSearchParams({grant_type:'refresh_token',refresh_token:rf});let r=await fetch(`https://securetoken.googleapis.com/v1/token?key=${firebaseConfig.apiKey}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});let t=await r.text();locCount(b.toString().length+t.length);if(r.ok){let j=JSON.parse(t);localStorage.setItem('fb_tok',j.id_token);localStorage.setItem('fb_rf',j.refresh_token||rf);localStorage.setItem('fb_exp',Date.now()+3000000);return j.id_token}}let b=JSON.stringify({returnSecureToken:true});let r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${firebaseConfig.apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:b});let t=await r.text();locCount(b.length+t.length);if(!r.ok)throw Error('Firebase 익명 인증 실패');let j=JSON.parse(t);localStorage.setItem('fb_tok',j.idToken);localStorage.setItem('fb_rf',j.refreshToken);localStorage.setItem('fb_uid',j.localId);localStorage.setItem('fb_exp',Date.now()+3000000);return j.idToken}
function dbPath(slot=''){return `${firebaseConfig.databaseURL}/locations/${TRIP_CODE}${slot?'/'+slot:''}.json`}
function histPath(slot='',point=''){return `${firebaseConfig.databaseURL}/locationHistory/${TRIP_CODE}${slot?'/'+slot:''}${point?'/'+point:''}.json`}
function locOwnerPath(slot=''){return `${firebaseConfig.databaseURL}/locationOwners/${TRIP_CODE}${slot?'/'+slot:''}.json`}
function locControlPath(){return `${firebaseConfig.databaseURL}/locationControl/${TRIP_CODE}.json`}
async function locCheckResetControl(tk){
  if(!currentUser)return false;
  try{
    tk=tk||await token();
    const r=await fetch(locControlPath()+`?auth=${encodeURIComponent(tk)}`,{cache:'no-store'}),txt=await r.text();locCount(txt.length);
    if(!r.ok)return false;
    const j=txt&&txt!=='null'?JSON.parse(txt):null,resetAt=+(j?.resetAt||0),seen=+(localStorage.getItem('loc_reset_seen')||0);
    if(resetAt>seen){
      localStorage.setItem('loc_reset_seen',String(resetAt));
      clearInterval(locTimer);locTimer=null;localStorage.setItem('loc_sharing','0');localStorage.removeItem('loc_lastwrite');locLastWrite=0;
      const st=document.getElementById('locShareStatus');if(st)st.textContent='관리자가 위치정보를 초기화했습니다 · 공유 OFF · 필요하면 다시 시작하세요';
      updateLiveLocChip();return true;
    }
  }catch(_){ }
  return false;
}
async function locEnsureOwnerBinding(tk){
  if(!currentUser)throw Error('로그인이 필요합니다.');
  tk=tk||await token();const uid=localStorage.getItem('fb_uid')||'';if(!uid)throw Error('Firebase 사용자 확인 실패');
  const data={uid,slot:currentUser.slot,name:currentUser.name},body=JSON.stringify(data);
  const r=await fetch(locOwnerPath(currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body}),txt=await r.text();locCount(body.length+txt.length);
  if(!r.ok)throw Error('위치 이력 본인확인 연결 실패 — 최신 Firebase Rules를 적용해 주세요.');
  return true;
}
function attCurrentPath(){return `${firebaseConfig.databaseURL}/attendanceCurrent/${TRIP_CODE}.json`}
function attPath(event='',slot=''){return `${firebaseConfig.databaseURL}/attendance/${TRIP_CODE}${event?'/'+event:''}${slot?'/'+slot:''}.json`}
function getPos(high=false){return new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(res,e=>rej(Error(e.code===1?'위치 권한을 허용해 주세요.':'위치 확인 실패')),{enableHighAccuracy:high,timeout:15000,maximumAge:high?0:60000}):rej(Error('위치 기능 미지원')))}
async function locRefreshAll(manual=false){if(!currentUser)return;if(navigator.onLine===false){let e=document.getElementById('locBackendState');if(e){e.textContent='오프라인 · 일행 위치 조회·전송은 인터넷 연결 필요';e.className='note'}renderRoster();return}try{let tk=await token();await locCheckResetControl(tk);let r=await fetch(dbPath()+`?auth=${encodeURIComponent(tk)}`,{cache:'no-store'}),t=await r.text();locCount(t.length);if(!r.ok)throw Error('위치 DB 읽기 실패 — Rules 확인');let j=t&&t!=='null'?JSON.parse(t):{},now=Date.now();locCache={};Object.entries(j||{}).forEach(([k,v])=>{if(APP_BY_SLOT[k]&&v&&v.lat!=null&&now-(v.ts||0)<SHOWMAX)locCache[k]=v});localStorage.setItem('loc_read',Date.now());document.getElementById('locBackendState').textContent='Firebase 위치 연결 정상 · 최근 24시간만 조회·표시';document.getElementById('locBackendState').className='ok';renderRoster()}catch(e){document.getElementById('locBackendState').textContent=e.message||e;document.getElementById('locBackendState').className='note';if(manual)alert(e.message||e)}}
async function locWritePosition(p){if(!currentUser)throw Error('로그인이 필요합니다.');let tk=await token();if(await locCheckResetControl(tk))throw Error('관리자 초기화로 위치공유가 중지되었습니다. 필요하면 위치 공유 시작을 다시 눌러 주세요.');let uid=localStorage.getItem('fb_uid')||'',data={uid,slot:currentUser.slot,group:currentUser.group,name:currentUser.name,lat:+p.coords.latitude.toFixed(5),lng:+p.coords.longitude.toFixed(5),accuracy:Math.round(p.coords.accuracy||0),ts:Date.now(),pageState:document.hidden?'background':'foreground'},b=JSON.stringify(data);let r=await fetch(dbPath(currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:b}),t=await r.text();locCount(b.length+t.length);if(!r.ok)throw Error('현재 위치 저장 실패 — Firebase Rules 확인');let historyOk=true;try{await locEnsureOwnerBinding(tk);let hb=JSON.stringify(data),hr=await fetch(histPath(currentUser.slot,String(data.ts))+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:hb}),ht=await hr.text();locCount(hb.length+ht.length);if(!hr.ok)historyOk=false}catch(e){historyOk=false}locCache[currentUser.slot]=data;locLastPos=p;locLastWrite=data.ts;localStorage.setItem('loc_lastwrite',String(data.ts));let st=document.getElementById('locShareStatus');if(st)st.textContent=`전송중 · ${lastSeenClock(data.ts)} · 정확도 약 ${data.accuracy}m${historyOk?' · 내 24시간 이력 저장':' · 이력 저장 실패'}`;updateLiveLocChip();renderRoster();return true}
async function locUpdateNow(high=false){if(!currentUser)return;if(navigator.onLine===false){let st=document.getElementById('locShareStatus');if(st)st.textContent='오프라인 · 위치 전송에는 인터넷 연결이 필요합니다.';return}try{let p=await getPos(high);await locWritePosition(p)}catch(e){let st=document.getElementById('locShareStatus');if(st)st.textContent=e.message||e}}
function locStartTimer(){clearInterval(locTimer);locTimer=setInterval(()=>{if(localStorage.getItem('loc_sharing')==='1'&&!document.hidden)locUpdateNow(false)},300000)}
async function locStartSharing(){if(!currentUser){document.getElementById('loginScreen').classList.remove('hidden');return}localStorage.setItem('loc_sharing','1');localStorage.setItem('loc_slot',currentUser.slot);localStorage.setItem('loc_name',currentUser.name);await locUpdateNow(false);locStartTimer();updateLiveLocChip()}
async function locStopSharing(){clearInterval(locTimer);locTimer=null;localStorage.setItem('loc_sharing','0');if(currentUser){try{let tk=await token(),r=await fetch(dbPath(currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'DELETE'}),t=await r.text();locCount(t.length);delete locCache[currentUser.slot]}catch(e){}}let st=document.getElementById('locShareStatus');if(st)st.textContent='공유 OFF · 이동이력은 최근 24시간만 유지';updateLiveLocChip();renderRoster()}
function locUserMatchesFilter(u){return locFilter==='all'||(locFilter==='prof'&&u.group===0)||String(u.group)===locFilter}
function locSetFilter(f,btn){locFilter=f;document.querySelectorAll('#locFilters button').forEach(x=>x.classList.toggle('active',x===btn));renderRoster();updateMarkers()}
function renderRoster(){let box=document.getElementById('locRoster');if(!box)return;box.innerHTML='';let live=0,recent=0,old=0;APP_USERS.forEach(u=>{let r=locCache[u.slot];if(r&&Date.now()-r.ts<=LIVE5)live++;else if(r&&Date.now()-r.ts<=RECENT30)recent++;else old++});let groups=[1,2,3,4,0];groups.forEach(g=>{let members=APP_USERS.filter(u=>u.group===g&&locUserMatchesFilter(u)).sort((a,b)=>a.groupOrder-b.groupOrder);if(!members.length)return;let h=document.createElement('div');h.className='grouphead';h.innerHTML=`<span class="legend-ring" style="border-color:${locGroupColor(g)};vertical-align:-3px"></span> ${g===0?'교수님 · 인솔':g+'조 · '+members.length+'명'+(members.find(x=>x.leader)?' · 조장 '+members.find(x=>x.leader).name:'')}`;box.appendChild(h);members.forEach(u=>{let r=locCache[u.slot],ai=locAgeInfo(r?.ts),role=u.group===0?'교수님':(u.leader?'조장':'조원'),pos=r?`<span class="loc-age-badge">${ai.label}</span> · 마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)}) · ±${Math.round(r.accuracy||0)}m`:'최근 24시간 위치 없음',isSelf=!!currentUser&&u.slot===currentUser.slot;let row=document.createElement('div');row.className='person';let mapBtn=isSelf?`<button class="mini" onclick="locLoadHistory('${u.slot}',true)">내 이동이력</button>`:`<button class="mini" ${r?'':'disabled'} onclick="${r?`window.open('https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}','_blank')`:''}">지도</button>`;row.innerHTML=`<span class="dot ${ai.cls}" style="box-shadow:0 0 0 4px ${locGroupColor(u.group)}"></span><div><div class="pname">${esc(u.name)}<small>${esc(u.org)} · ${esc(u.title)}</small></div><div class="pmeta">${u.group===0?'<span class="prof-badge">교수님</span>':`<span class="loc-role">${u.group}조 ${role}</span>`} · ${pos}</div></div><div class="loc-actions-mini"><button class="mini" onclick="locOpenPerson('${u.slot}')">상세</button>${mapBtn}</div>`;box.appendChild(row)})});document.getElementById('locLiveCount').textContent=live;document.getElementById('locStaleCount').textContent=recent;document.getElementById('locOffCount').textContent=old;let lr=localStorage.getItem('loc_read');document.getElementById('locLastRefresh').textContent=lr?new Date(+lr).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'-';updateLiveLocChip();updateMarkers()}
async function locOpenPerson(slot){let u=APP_BY_SLOT[slot],r=locCache[slot],box=document.getElementById('locPersonDetail');if(!u)return;let ai=locAgeInfo(r?.ts),isSelf=!!currentUser&&slot===currentUser.slot;box.classList.add('show');let action='';if(isSelf){action=`<button class="primary" onclick="locLoadHistory('${slot}',true)">🗺 Google 지도 · 내 24시간 이동이력</button>`}else if(r){action=`<button onclick="window.open('https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}','_blank')">Google 지도 · 현재 위치</button>`}box.innerHTML=`<div class="loc-simple-head"><div><h3>${esc(u.name)} · ${userGroupText(u)}</h3><div class="small muted">${esc(u.org)} · ${esc(u.title)}</div></div><button onclick="document.getElementById('locPersonDetail').classList.remove('show')">닫기</button></div>${r?`<p><b>${ai.label}</b> · 마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)})<br>위치 ${r.lat.toFixed(5)}, ${r.lng.toFixed(5)} · 정확도 약 ${Math.round(r.accuracy||0)}m</p>`:'<p class="muted">최근 24시간 내 공유된 현재 위치가 없습니다.</p>'}${isSelf?'<p class="small muted">이동이력은 본인에게만 최근 24시간 범위로 표시됩니다.</p>':''}<div class="actions">${action}</div>`;box.scrollIntoView({behavior:'smooth',block:'center'})}
async function locLoadHistory(slot,draw=false){if(!currentUser||slot!==currentUser.slot){alert('이동이력은 본인 기록만 볼 수 있습니다.');return}try{let tk=await token(),min=String(Date.now()-SHOWMAX),url=histPath(slot)+`?auth=${encodeURIComponent(tk)}&orderBy=%22%24key%22&startAt=%22${min}%22&limitToLast=320`,r=await fetch(url,{cache:'no-store'}),t=await r.text();locCount(t.length);if(!r.ok)throw Error('내 이동이력 읽기 실패 — 최신 Firebase Rules를 확인해 주세요.');let j=t&&t!=='null'?JSON.parse(t):{},cut=Date.now()-SHOWMAX,pts=Object.values(j||{}).filter(x=>x&&x.lat!=null&&+x.ts>=cut&&x.uid===(localStorage.getItem('fb_uid')||x.uid)).sort((a,b)=>a.ts-b.ts);if(!pts.length){alert('최근 24시간 내 저장된 내 이동이력이 없습니다.');return}if(draw){locToggleMap(true);setTimeout(()=>locDrawHistory(pts),450)}}catch(e){alert(e.message||e)}}
async function locAdminResetAll(){
  if(!currentUser||currentUser.name!=='한상호'){alert('전체 위치정보 초기화는 관리자 한상호만 실행할 수 있습니다.');return}
  if(!confirm('전체 28명의 현재 위치와 저장된 이동이력을 모두 삭제합니다. 계속할까요?'))return;
  if(!confirm('삭제 후 복구할 수 없습니다. 위치공유 중인 사용자는 초기화 신호를 확인하면 공유가 OFF되며, 다시 공유하려면 각자 직접 시작해야 합니다. 정말 초기화할까요?'))return;
  const btn=document.getElementById('locAdminResetBtn');if(btn){btn.disabled=true;btn.textContent='초기화 중…'}
  try{
    let tk=await token();
    // 관리자 소유 바인딩이 없으면 현재 위치를 1회 저장해 바인딩을 만든다.
    let or=await fetch(locOwnerPath(currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{cache:'no-store'}),ot=await or.text();locCount(ot.length);
    if(!or.ok||!ot||ot==='null'){
      // 새 브라우저가 과거 초기화 신호를 처음 보는 경우 먼저 확인 처리한 뒤 관리자 바인딩을 만든다.
      await locCheckResetControl(tk);localStorage.setItem('loc_sharing','1');
      let p=await getPos(true);await locWritePosition(p);tk=await token();
    }
    const uid=localStorage.getItem('fb_uid')||'',resetAt=Date.now(),control={resetAt,resetByUid:uid,resetByName:'한상호'};
    let cb=JSON.stringify(control),cr=await fetch(locControlPath()+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:cb}),ct=await cr.text();locCount(cb.length+ct.length);if(!cr.ok)throw Error('초기화 신호 저장 실패 — 최신 Firebase Rules가 필요합니다.');
    for(const url of [histPath(),dbPath(),locOwnerPath()]){let rr=await fetch(url+`?auth=${encodeURIComponent(tk)}`,{method:'DELETE'}),tt=await rr.text();locCount(tt.length);if(!rr.ok)throw Error('전체 위치정보 삭제가 거부되었습니다 — Firebase Rules를 확인해 주세요.')}
    clearInterval(locTimer);locTimer=null;localStorage.setItem('loc_sharing','0');localStorage.setItem('loc_reset_seen',String(resetAt));localStorage.removeItem('loc_lastwrite');locLastWrite=0;locCache={};window.LocationSession?.applyAdminReset?.(resetAt);renderRoster();
    const st=document.getElementById('locShareStatus');if(st)st.textContent='관리자 전체 초기화 완료 · 위치공유 OFF';
    alert('전체 위치정보를 초기화했습니다. 현재 위치와 이동이력은 삭제되었으며, 각 사용자가 다시 위치공유를 시작하기 전까지 새 위치가 올라오지 않습니다.');
  }catch(e){alert(e.message||e)}finally{if(btn){btn.disabled=false;btn.textContent='전체 위치정보 리셋'}}
}
let locMapEngine='',googleOverlays=[],googleInfo=null,googleHistory=null,googleLoadStarted=false,googleLoadFailed=false,googleLoadTimer=null,googleScriptEl=null;
function locToggleMap(force=false){let b=document.getElementById('locMap');if(!force&&b.classList.contains('show')){b.classList.remove('show');return}b.classList.add('show');if(navigator.onLine===false&&!window.google?.maps&&!window.L){b.innerHTML='<div class="offline-map-placeholder"><b>지도는 인터넷 연결이 필요합니다.</b><span>일정·관광지 설명·호텔 정보는 오프라인에서도 계속 볼 수 있습니다.</span></div>';locSetEngineText('오프라인 · 지도 연결 필요');return}locEnsureMap()}
function locSetEngineText(t){let e=document.getElementById('locMapEngine');if(e)e.textContent='지도 엔진: '+t}
function locDestroyLeaflet(){if(mapObj&&typeof mapObj.remove==='function'&&!mapObj.getDiv){try{mapObj.remove()}catch(_){ }mapObj=null;markers=[];historyLayer=null}}
function locActivateGoogleMap(label='Google Maps · 조별 색상'){if(!window.google?.maps)return false;if(googleLoadTimer){clearTimeout(googleLoadTimer);googleLoadTimer=null}googleLoadStarted=false;googleLoadFailed=false;locDestroyLeaflet();locMapEngine='google';locSetEngineText(label);initGoogleMap();return true}
function locEnsureMap(){if(locMapEngine==='google'&&window.google?.maps){initGoogleMap();return}if(window.google?.maps){locActivateGoogleMap();return}if(locMapEngine==='leaflet'&&window.L){initLeafletMap();return}locLoadGoogleMap()}
function locLoadGoogleMap(){if(locActivateGoogleMap())return;if(navigator.onLine===false){googleLoadStarted=false;googleLoadFailed=false;locSetEngineText('오프라인 · Google Maps 연결 필요');let b=document.getElementById('locMap');if(b)b.innerHTML='<div class="offline-map-placeholder"><b>오프라인 상태입니다.</b><span>Google Maps는 인터넷 연결 후 사용할 수 있습니다.</span></div>';return;}if(googleLoadFailed){locLoadLeaflet('Google Maps 연결 오류 · 임시 OpenStreetMap · “Google 지도 다시 연결”로 재시도');return}if(googleLoadStarted)return;googleLoadStarted=true;locSetEngineText('Google Maps 불러오는 중…');window.gm_authFailure=function(){if(googleLoadTimer){clearTimeout(googleLoadTimer);googleLoadTimer=null}googleLoadFailed=true;googleLoadStarted=false;locLoadLeaflet('Google Maps API 인증·도메인·결제 설정 오류 · 임시 OpenStreetMap')};window.__croGoogleMapReady=function(){locActivateGoogleMap('Google Maps · 조별 색상')};let sc=document.createElement('script');googleScriptEl=sc;sc.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(GOOGLE_MAPS_API_KEY)}&callback=__croGoogleMapReady&v=weekly&loading=async`;sc.async=true;sc.defer=true;sc.onerror=()=>{if(googleLoadTimer){clearTimeout(googleLoadTimer);googleLoadTimer=null}googleLoadFailed=true;googleLoadStarted=false;locLoadLeaflet('Google Maps 네트워크 로드 실패 · 임시 OpenStreetMap')};document.head.appendChild(sc);googleLoadTimer=setTimeout(()=>{googleLoadTimer=null;if(locActivateGoogleMap())return;googleLoadStarted=false;googleLoadFailed=false;locLoadLeaflet('Google Maps 연결 지연 · 임시 OpenStreetMap · Google Maps가 로드되면 자동 복귀')},20000)}
function locRetryGoogleMap(){if(navigator.onLine===false){locSetEngineText('오프라인 · Google Maps 연결 필요');window.showAppToast?.('Google 지도는 인터넷 연결이 필요합니다.');return}if(googleLoadTimer){clearTimeout(googleLoadTimer);googleLoadTimer=null}googleLoadFailed=false;googleLoadStarted=false;if(locActivateGoogleMap('Google Maps · 조별 색상'))return;if(googleScriptEl?.isConnected){try{googleScriptEl.remove()}catch(_){ }}googleScriptEl=null;locMapEngine='';locSetEngineText('Google Maps 다시 연결 중…');locLoadGoogleMap()}
window.locRetryGoogleMap=locRetryGoogleMap;
function initGoogleMap(){let box=document.getElementById('locMap');if(!box||!window.google?.maps)return;if(locMapEngine!=='google')locMapEngine='google';if(!mapObj||!mapObj.getDiv){locDestroyLeaflet();box.innerHTML='';mapObj=new google.maps.Map(box,{center:{lat:44.1,lng:16.2},zoom:6,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,gestureHandling:'greedy'});googleInfo=new google.maps.InfoWindow()}setTimeout(()=>google.maps.event.trigger(mapObj,'resize'),120);updateMarkers()}
function makeGoogleOverlay(u,r,ai){class M extends google.maps.OverlayView{onAdd(){let d=document.createElement('div');d.className='g-overlay';let group=u.group===0?'교수님':`${u.group}조`;d.innerHTML=`<div class="dual-marker" style="--group:${locGroupColor(u.group)};--age:${ai.color}"><span class="dual-label">${esc(u.name)} · ${ago(r.ts)}</span></div>`;d.onclick=()=>{googleInfo.setContent(`<div style="font-size:13px;line-height:1.65"><b>${esc(u.name)}</b> · ${group}<br><b>${ai.label}</b> · 마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)})<br>GPS 정확도 약 ${Math.round(r.accuracy||0)}m<br><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}">Google 지도에서 열기</a></div>`);googleInfo.setPosition({lat:r.lat,lng:r.lng});googleInfo.open(mapObj)};this.div=d;this.getPanes().overlayMouseTarget.appendChild(d)}draw(){let p=this.getProjection().fromLatLngToDivPixel(new google.maps.LatLng(r.lat,r.lng));if(this.div){this.div.style.left=p.x+'px';this.div.style.top=p.y+'px'}}onRemove(){this.div?.remove();this.div=null}}let ov=new M();ov.setMap(mapObj);return ov}
function updateMarkers(){if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv){googleOverlays.forEach(x=>x.setMap(null));googleOverlays=[];if(googleHistory){googleHistory.setMap(null);googleHistory=null}let bounds=new google.maps.LatLngBounds(),count=0;Object.entries(locCache).forEach(([slot,r])=>{let u=APP_BY_SLOT[slot];if(!u||!locUserMatchesFilter(u)||Date.now()-(r.ts||0)>SHOWMAX)return;let ai=locAgeInfo(r.ts);googleOverlays.push(makeGoogleOverlay(u,r,ai));bounds.extend({lat:r.lat,lng:r.lng});count++});if(count===1){mapObj.setCenter(bounds.getCenter());mapObj.setZoom(16)}else if(count>1)mapObj.fitBounds(bounds,55);return}updateLeafletMarkers()}
function locDrawHistory(pts){if(!pts.length)return;locToggleMap(true);if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv){if(googleHistory)googleHistory.setMap(null);googleHistory=new google.maps.Polyline({path:pts.map(x=>({lat:x.lat,lng:x.lng})),strokeColor:'#1f6f9c',strokeOpacity:.9,strokeWeight:4,map:mapObj});let b=new google.maps.LatLngBounds();pts.forEach(x=>b.extend({lat:x.lat,lng:x.lng}));mapObj.fitBounds(b,45);return}if(locMapEngine==='leaflet'&&window.L){if(historyLayer)mapObj.removeLayer(historyLayer);historyLayer=L.polyline(pts.map(x=>[x.lat,x.lng]),{weight:4,opacity:.8}).addTo(mapObj);mapObj.fitBounds(historyLayer.getBounds(),{padding:[40,40],maxZoom:17})}}
function locLoadLeaflet(msg='OpenStreetMap · 조별 색상'){if(navigator.onLine===false&&!window.L){locMapEngine='';locSetEngineText('오프라인 · 지도 연결 필요');let box=document.getElementById('locMap');if(box)box.innerHTML='<div class="offline-map-placeholder"><b>지도는 인터넷 연결이 필요합니다.</b><span>연결되면 Google Maps를 우선 사용합니다.</span></div>';return}locMapEngine='leaflet';locSetEngineText(msg);let box=document.getElementById('locMap');if(mapObj?.getDiv){mapObj=null;box.innerHTML=''}if(window.L){initLeafletMap();return}let c=document.createElement('link');c.rel='stylesheet';c.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(c);let sc=document.createElement('script');sc.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';sc.onload=initLeafletMap;sc.onerror=()=>box.innerHTML='<div style="padding:20px">지도를 불러오지 못했습니다. 사람별 ‘지도’ 버튼을 이용해 주세요.</div>';document.body.appendChild(sc)}
function initLeafletMap(){let box=document.getElementById('locMap');if(!window.L||!box)return;if(!mapObj||!mapObj.invalidateSize){box.innerHTML='';mapObj=L.map('locMap',{zoomControl:true}).setView([44.1,16.2],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapObj)}setTimeout(()=>mapObj.invalidateSize(),120);updateLeafletMarkers()}
function updateLeafletMarkers(){if(locMapEngine!=='leaflet'||!mapObj||!window.L)return;markers.forEach(m=>mapObj.removeLayer(m));markers=[];if(historyLayer){mapObj.removeLayer(historyLayer);historyLayer=null}let pts=[];Object.entries(locCache).forEach(([slot,r])=>{let u=APP_BY_SLOT[slot];if(!u||!locUserMatchesFilter(u)||Date.now()-(r.ts||0)>SHOWMAX)return;let ai=locAgeInfo(r.ts),group=u.group===0?'교수님':`${u.group}조`,html=`<div class="dual-marker" style="--group:${locGroupColor(u.group)};--age:${ai.color}"><span class="dual-label">${esc(u.name)} · ${ago(r.ts)}</span></div>`,icon=L.divIcon({className:'dual-leaf',html,iconSize:[22,22],iconAnchor:[11,11]});let m=L.marker([r.lat,r.lng],{icon}).addTo(mapObj).bindPopup(`<b>${esc(u.name)}</b><br>${group} · <b>${ai.label}</b><br>마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)})<br>GPS 정확도 약 ${Math.round(r.accuracy||0)}m<br><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}">Google 지도에서 열기</a>`);markers.push(m);pts.push([r.lat,r.lng])});if(pts.length===1)mapObj.setView(pts[0],16);else if(pts.length>1)mapObj.fitBounds(pts,{padding:[55,55],maxZoom:17})}
function locFullScreenMap(){let b=document.getElementById('locMap');b.classList.add('show','fullscreen');document.body.classList.add('map-fullscreen');document.getElementById('locMapClose').classList.add('show');locEnsureMap();setTimeout(()=>{if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv)google.maps.event.trigger(mapObj,'resize');else if(mapObj?.invalidateSize)mapObj.invalidateSize()},150)}
function locExitFullScreenMap(){document.getElementById('locMap').classList.remove('fullscreen');document.body.classList.remove('map-fullscreen');document.getElementById('locMapClose').classList.remove('show');setTimeout(()=>{if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv)google.maps.event.trigger(mapObj,'resize');else if(mapObj?.invalidateSize)mapObj.invalidateSize()},150)}
async function locTestConnection(){try{await token();await locRefreshAll(true);alert('Firebase 인증과 위치 DB 조회가 정상입니다.')}catch(e){alert(e.message||e)}}
function locLifecycleSetup(){document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(localStorage.getItem('loc_sharing')==='1'&&Date.now()-locLastWrite>300000)locUpdateNow(false);locRefreshAll(false);attRefresh(false)}});window.addEventListener('online',()=>{locRefreshAll(false);attRefresh(false)});if(localStorage.getItem('loc_sharing')==='1')setTimeout(()=>{if(!document.hidden){locUpdateNow(false);locStartTimer()}},1200);pollTimer=setInterval(()=>{if(!document.hidden)locRefreshAll(false)},120000)}

// Attendance implementation: js/attendance.js (MIX02).

document.getElementById('loginName')?.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('loginPass')?.focus()});document.getElementById('loginPass')?.addEventListener('keydown',e=>{if(e.key==='Enter')appLogin()});
appInitLogin();updateLiveLocChip();setInterval(()=>{updateLiveLocChip();if(!document.hidden){renderRoster();attRender()}},60000);

function filterTeamRoster(q){q=String(q||'').trim().toLowerCase();document.querySelectorAll('#teamAllRoster .team-member').forEach(el=>{let hay=(el.dataset.name+' '+el.dataset.org+' '+el.textContent).toLowerCase();el.style.display=!q||hay.includes(q)?'grid':'none'})}
// Preparation checklist implementation: js/preparation.js (MIX02).
