

// Google Maps JavaScript API key (client-side web key)




const LOC_BY_SLOT=Object.fromEntries(LOC_MEMBERS.map(x=>[x.slot,x]));

// font size controls
function applyFontSize(px){px=Math.max(17,Math.min(25,px));document.documentElement.style.setProperty('--fs',px+'px');localStorage.setItem('cro_font_size',String(px))}
function fontStep(d){let now=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--fs'))||19;applyFontSize(now+d)}
function fontReset(){applyFontSize(19)}
applyFontSize(+(localStorage.getItem('cro_font_size')||19));

function localDate(){let f=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zagreb',year:'numeric',month:'2-digit',day:'2-digit'});return f.format(new Date())}


function _normPlaceText(s){return String(s||'').toLowerCase().replace(/[^0-9a-z가-힣]+/g,' ').trim()}
function _placeTokens(s){let stop=new Set(['두브로브니크','스플리트','트로기르','자다르','자그레브','로마','핵심','관광','구시가지','코스','전체','성','the','old','town']);return _normPlaceText(s).split(/\s+/).filter(t=>t.length>1&&!stop.has(t))}
function _matchedAttractions(anchor,name){let city=document.querySelector(anchor);if(!city)return[];let q=_placeTokens(name),items=[...city.querySelectorAll('.attraction')];if(!q.length)return[];let scored=items.map(el=>{let title=el.querySelector('h4')?.textContent||'',nt=_placeTokens(title),score=q.reduce((s,t)=>s+(nt.some(n=>n.includes(t)||t.includes(n))?1:0),0);return {el,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);let best=scored[0]?.score||0;return scored.filter(x=>x.score>=Math.max(1,best-1)).slice(0,2).map(x=>x.el)}
function _inlineAttractionDetail(x){let city=document.querySelector(x.a),overview=city?.querySelector('.city-overview')?.textContent?.trim()||'',history=city?.querySelector('.read-more>p')?.textContent?.trim()||'',matches=_matchedAttractions(x.a,x.n),matchedHtml=matches.map(el=>el.outerHTML).join('');let route=city?.querySelector('.city-route-tip')?.outerHTML||'';return `<details class="inline-attraction-detail" ontoggle="singleOpenDetail(this)"><summary>상세보기</summary><div class="inline-detail-body">${overview?`<h5>📖 이 장소를 이해하기 위한 도시 배경</h5><div class="inline-city-context">${overview}</div>`:''}${history?`<div class="inline-history"><b>역사 한눈에</b><br>${history}</div>`:''}${matchedHtml||`<div class="inline-fallback"><b>${x.n}</b><br>${x.p}<br><br><b>꼭 볼 것</b><br>${x.m}<br><br><b>관람시간</b> ${x.t}<br><b>입장·요금</b> ${x.price}</div>`}${route}<button type="button" class="inline-close" onclick="closeInlineDetail(this)">▲ 상세 닫기</button></div></details>`}
function singleOpenDetail(el){if(!el.open)return;let grid=el.closest('.day-attraction-grid');if(!grid)return;grid.querySelectorAll('.inline-attraction-detail[open]').forEach(d=>{if(d!==el)d.open=false})}
function closeInlineDetail(btn){let det=btn.closest('.inline-attraction-detail'),card=btn.closest('.day-attraction-card');if(det)det.open=false;if(card)requestAnimationFrame(()=>card.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function dayAttractionHtml(d){let arr=DAY_ATTRACTIONS[d.date]||[];if(!arr.length)return'';return `<h3 class="day-attraction-title">오늘 방문 관광지 · 바로 보는 가이드</h3><div class="day-guide-intro">일정 순서대로 배치했습니다. <b>상세보기</b>를 누르면 다른 곳으로 이동하지 않고 <b>바로 이 카드 아래에서 펼쳐집니다.</b> 다시 누르거나 아래의 ‘상세 닫기’로 접을 수 있습니다.</div><div class="day-attraction-grid">${arr.map(x=>`<article class="day-attraction-card"><h4>${x.n}</h4><p>${x.p}</p><div class="spot-meta"><span>⏱ ${x.t}</span><span>🎟 ${x.price}</span></div><div class="must-see"><b>무엇을 봐야 하나</b><br>${x.m}</div>${_inlineAttractionDetail(x)}<div class="btns"><a class="btn" target="_blank" rel="noopener" href="${x.book}">${x.book.includes('google.com/maps')?'📍 지도':'🎟 예매/공식'}</a></div></article>`).join('')}</div>`}
function expectedHourlyHtml(d){let w=WEATHER_SPOTS[d.date];if(!w)return'<div class="note">해당 날짜 기상 기준점이 없습니다.</div>';let vals=[['08:00',w.lo+2],['11:00',Math.round((w.lo+w.hi)/2)],['14:00',w.hi],['17:00',w.hi-2],['20:00',Math.max(w.lo+2,w.hi-5)]];return `<div class="day-weather-head"><b>${w.name} · 시간대별 장기 참고</b><small>실제 시간예보는 약 16일 전부터 자동 전환</small></div><div class="day-hourly">${vals.map(v=>`<div class="day-hour"><div class="t">${v[0]}</div><div class="i">🌤️</div><div class="temp">약 ${v[1]}°</div><div class="sub">평년 참고<br>강수확률 미제공</div></div>`).join('')}</div>`}
async function loadDayWeather(i){let d=days[i],box=document.getElementById(`dayWeather-${i}`);if(!box)return;let w=WEATHER_SPOTS[d.date];if(!w){box.innerHTML='<div class="note">날씨 정보가 없습니다.</div>';return}let diff=daysDiff(d.date,croDate());if(diff>15||diff<0){box.innerHTML=expectedHourlyHtml(d);return}box.innerHTML='<div class="small muted">시간대별 예보 불러오는 중…</div>';try{let url=`https://api.open-meteo.com/v1/forecast?latitude=${w.lat}&longitude=${w.lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m&timezone=Europe%2FZagreb&start_date=${d.date}&end_date=${d.date}`;let j=await tinyFetch(url),times=j.hourly?.time||[],temps=j.hourly?.temperature_2m||[],feel=j.hourly?.apparent_temperature||[],rain=j.hourly?.precipitation_probability||[],codes=j.hourly?.weather_code||[],wind=j.hourly?.wind_speed_10m||[],hours=['08','11','14','17','20'],idx=hours.map(h=>times.findIndex(t=>t.slice(11,13)===h)).filter(x=>x>=0);box.innerHTML=`<div class="day-weather-head"><b>${w.name} · ${d.date.slice(5).replace('-','/')} 시간대별 예보</b><small>${fmtFetchTime()} 갱신</small></div><div class="day-hourly">${idx.map(k=>`<div class="day-hour"><div class="t">${times[k].slice(11,16)}</div><div class="i">${weatherIcon(codes[k])}</div><div class="temp">${Math.round(temps[k])}°</div><div class="sub">체감 ${Math.round(feel[k]??temps[k])}°<br>비 ${rain[k]??0}% · 바람 ${Math.round(wind[k]??0)}km/h</div></div>`).join('')}</div>`}catch(e){box.innerHTML=expectedHourlyHtml(d)}}
function renderDays(){let tabs=document.getElementById('dayTabs'),wrap=document.getElementById('dayPanels');tabs.innerHTML='';wrap.innerHTML='';days.forEach((d,i)=>{let b=document.createElement('button');b.className='tab';b.textContent=d.date.slice(5).replace('-','/');b.onclick=()=>selectDay(i);tabs.appendChild(b);let p=document.createElement('div');p.className='panel';let flow=(d.flow||[]).map((x,j)=>`${j?'<span class="flow-arrow">›</span>':''}<span class="flow-stop"><span class="flow-pill">${x}</span></span>`).join('');let moves=(d.moves||[]).map(m=>`<div class="move-row"><span class="move-mode">${m[0]}</span><span class="move-route">${m[1]}</span><span class="move-time">${m[2]}</span></div>`).join('');let gl=(d.guides||[]).map(g=>`<a href="${g[1]}">📖 ${g[0]} 상세가이드</a>`).join('');p.innerHTML=`<div class="day-summary"><h3>${d.date} · ${d.title}</h3><p><b>추천 이동순서</b> ${d.route}</p><div class="day-flow">${flow}</div><div class="day-guide-links">${gl}</div>${d.map?`<div class="btns"><a class="btn" target="_blank" rel="noopener" href="${d.map}">📍 Google 전체 동선</a></div>`:''}</div><div class="recommended-flow"><b>이 날짜를 이렇게 보면 좋습니다.</b><br>공식 일정의 순서를 유지하면서 되돌아가는 이동을 줄이고, 식사·집결·차량 탑승시간을 먼저 확보한 뒤 핵심 관광지를 이어서 보도록 구성했습니다.</div><div class="day-weather-box" id="dayWeather-${i}">${expectedHourlyHtml(d)}</div><div class="day-main-grid"><div class="card"><h3>추천 일정 · 공식 일정 기준</h3><div class="timeline">${d.events.map(e=>`<div class="event"><span class="time">${e[0]}</span>${e[1]}</div>`).join('')}</div>${d.meal?`<div class="meal"><b>식사 운영</b><br>${d.meal}</div>`:''}</div><div class="card"><h3>구간별 이동시간</h3><div class="move-list">${moves}</div><div class="route-source">※ 도시 간 차량시간은 설명회 안내책자를 우선했고, 구시가지 도보시간은 일반적인 보행 기준입니다. 28명 승하차·주차·화장실 이용에 따라 여유시간이 더 필요할 수 있습니다.</div></div></div>${dayAttractionHtml(d)}`;wrap.appendChild(p)});let idx=days.findIndex(x=>x.date===localDate());selectDay(idx>=0?idx:0);let d=days[idx>=0?idx:0];document.getElementById('todayDate').textContent='현지 '+localDate();document.getElementById('todayTitle').textContent=d.title;document.getElementById('todayRoute').textContent=d.route;document.getElementById('todayBtns').innerHTML=(d.map?`<a class="btn primary" target="_blank" rel="noopener" href="${d.map}">오늘 지도</a>`:'')+`<a class="btn" href="#schedule">오늘 상세일정</a>`+(d.guides&&d.guides[0]?`<a class="btn" href="${d.guides[0][1]}">오늘 관광가이드</a>`:'');}
function selectDay(i){document.querySelectorAll('.tab').forEach((x,j)=>x.classList.toggle('active',i===j));document.querySelectorAll('.panel').forEach((x,j)=>x.classList.toggle('active',i===j));loadDayWeather(i);let p=document.querySelectorAll('.panel')[i];if(p&&location.hash==='#schedule')setTimeout(()=>p.scrollIntoView({behavior:'smooth',block:'start'}),40)}
// weather / fx lightweight
let autoBytes=0;
function addAuto(n){autoBytes+=n;let el=document.getElementById('liveData');if(el)el.textContent='🌐 자동데이터 '+(autoBytes/1024).toFixed(1)+' KB'}
async function tinyFetch(url){let r=await fetch(url,{cache:'no-store'}),t=await r.text();addAuto(t.length);if(!r.ok)throw Error(r.status);return JSON.parse(t)}

function croDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zagreb',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function weatherTarget(){let d=croDate();if(WEATHER_SPOTS[d])return {date:d,...WEATHER_SPOTS[d]};if(d<'2026-10-12')return {date:'2026-10-13',...WEATHER_SPOTS['2026-10-13']};return {date:'2026-10-18',...WEATHER_SPOTS['2026-10-18']}}
function weatherIcon(code){if(code===0)return'☀️';if([1,2].includes(code))return'🌤️';if(code===3)return'☁️';if([45,48].includes(code))return'🌫️';if([51,53,55,61,63,65,80,81,82].includes(code))return'🌧️';if([71,73,75,77,85,86].includes(code))return'🌨️';if([95,96,99].includes(code))return'⛈️';return'🌤️'}
function daysDiff(a,b){return Math.round((new Date(a+'T00:00:00Z')-new Date(b+'T00:00:00Z'))/86400000)}
function fmtFetchTime(){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Europe/Zagreb',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date())}
function renderExpectedOutlook(){let box=document.getElementById('tripWeatherOutlook');if(!box)return;box.innerHTML=Object.entries(WEATHER_SPOTS).map(([d,w])=>`<div class="outlook-item"><b>${d.slice(5).replace('-','/')} ${w.name}</b>예상 ${w.hi}° / ${w.lo}°</div>`).join('')}
function renderHourlyWeather(w,target){let box=document.getElementById('hourlyWeather');if(!box)return;let times=w.hourly?.time||[],temps=w.hourly?.temperature_2m||[],feels=w.hourly?.apparent_temperature||[],rain=w.hourly?.precipitation_probability||[],codes=w.hourly?.weather_code||[],wind=w.hourly?.wind_speed_10m||[];let nowHour=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Zagreb',hour:'2-digit',hour12:false}).format(new Date());let keep=[];for(let i=0;i<times.length;i++){let t=times[i],h=t.slice(11,13);if(target.date===croDate()){if(+h < Math.max(0,+nowHour-1))continue;if(keep.length>=12)break}else{if(+h<7||+h>21||(+h%2))continue;if(keep.length>=8)break}keep.push(i)}box.innerHTML=keep.map(i=>{let h=times[i].slice(11,16),isNow=target.date===croDate()&&times[i].slice(11,13)===String(nowHour).padStart(2,'0');return `<div class="hourly-item ${isNow?'now':''}"><div class="hourly-time">${h}</div><div class="hourly-icon">${weatherIcon(codes[i])}</div><div class="hourly-temp">${Math.round(temps[i])}°</div><div class="hourly-rain">비 ${rain[i]??0}% · ${Math.round(wind[i]??0)}km/h</div><div class="hourly-rain">체감 ${Math.round(feels[i]??temps[i])}°</div></div>`}).join('')}
async function refreshWeather(){let t=weatherTarget(),today=croDate(),diff=daysDiff(t.date,today),main=document.getElementById('liveWeatherMain'),upd=document.getElementById('weatherUpdated'),title=document.getElementById('weatherDetailTitle'),big=document.getElementById('weatherBigTemp'),meta=document.getElementById('weatherDetailMeta');renderExpectedOutlook();if(diff>15||diff<0){main.textContent=`🌤️ ${t.date.slice(5).replace('-','/')} ${t.name} 예상 ${t.hi}/${t.lo}°`;upd.textContent='장기 참고값 · 상세보기';title.textContent=`${t.name} · 여행 예상날씨`;big.textContent=`${t.hi}°`;meta.textContent=`최고 ${t.hi}° · 최저 ${t.lo}° · 상세 실시간 예보는 약 16일 전부터 자동 표시됩니다.`;document.getElementById('hourlyWeather').innerHTML='<div class="note" style="min-width:100%">현재는 장기예보 범위 밖입니다. 여행이 가까워지면 이 영역이 해당 날짜의 시간대별 기온·강수확률·바람으로 자동 전환됩니다.</div>';return}try{let url=`https://api.open-meteo.com/v1/forecast?latitude=${t.lat}&longitude=${t.lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code&timezone=Europe%2FZagreb&start_date=${t.date}&end_date=${t.date}`;let w=await tinyFetch(url),hi=Math.round(w.daily.temperature_2m_max[0]),lo=Math.round(w.daily.temperature_2m_min[0]),rain=w.daily.precipitation_probability_max?.[0]??0,code=w.daily.weather_code?.[0]??1,firstTemp=w.hourly?.temperature_2m?.[0];main.textContent=`${weatherIcon(code)} ${t.name} ${hi}/${lo}° · 비 ${rain}%`;upd.textContent=fmtFetchTime()+' 갱신 · 상세보기';title.textContent=`${t.date.slice(5).replace('-','/')} ${t.name} 시간대별 예보`;big.textContent=(firstTemp!=null?Math.round(firstTemp):hi)+'°';meta.textContent=`최고 ${hi}° · 최저 ${lo}° · 최대 강수확률 ${rain}% · ${fmtFetchTime()} 갱신`;renderHourlyWeather(w,t);}catch(e){main.textContent=`🌤️ ${t.name} 예상 ${t.hi}/${t.lo}°`;upd.textContent='예보 연결 실패 · 참고값';title.textContent=t.name+' 예상날씨';big.textContent=t.hi+'°';meta.textContent=`예상 최고 ${t.hi}° · 최저 ${t.lo}°`;}}
renderDays();
let currentEurKrw=1555;
function updateGuidePrices(rate){currentEurKrw=rate||1555;document.querySelectorAll('.eur-price').forEach(el=>{let e=parseFloat(el.dataset.eur||'0');if(!e)return;let won=Math.round(e*currentEurKrw/100)*100;el.textContent=`≈ ₩${won.toLocaleString('ko-KR')}`})}
async function refreshFx(){let main=document.getElementById('liveFxMain'),upd=document.getElementById('fxUpdated');try{let x=await tinyFetch('https://api.frankfurter.app/latest?from=EUR&to=KRW'),r=Math.round(x.rates.KRW);main.textContent='💶 €1 = ₩'+r.toLocaleString('ko-KR');upd.textContent=`${x.date||''} · ${fmtFetchTime()} 확인`;updateGuidePrices(r);}catch(e){main.textContent='💶 €1 ≈ ₩1,555';upd.textContent='저장 참고값 · 실시간 확인 실패';updateGuidePrices(1555);}}
async function refreshLive(){await Promise.allSettled([refreshWeather(),refreshFx()])}
refreshLive();setInterval(refreshLive,3600000);
// ===== login + location + attendance =====
const LIVE5=5*60*1000, RECENT15=15*60*1000, RECENT30=30*60*1000, HOUR1=60*60*1000, HOUR3=3*60*60*1000, HOUR6=6*60*60*1000, SHOWMAX=24*60*60*1000;
const APP_USERS=TEAM_MEMBERS.map(u=>{let lm=LOC_MEMBERS.find(x=>x.name===u.name);return {...u,slot:u.group===0?'prof1':(lm?.slot||''),groupLabel:u.group===0?'교수님':`${u.group}조`}});
const APP_BY_SLOT=Object.fromEntries(APP_USERS.map(u=>[u.slot,u]));
let currentUser=null,locCache={},locTimer=null,pollTimer=null,mapObj=null,markers=[],historyLayer=null,locBytes=0,locLastPos=null,locLastWrite=+(localStorage.getItem('loc_lastwrite')||0),locFilter='all';
let attCurrent=null,attChecks={},attTimer=null,attFilter='all';
function esc(x){return String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function userByName(n){return APP_USERS.find(u=>u.name===String(n||'').trim())}
function userGroupText(u){return u?.group===0?'교수님':`${u?.group||'-'}조${u?.leader?' · 조장':''}`}
function appInitLogin(){let saved=localStorage.getItem('cro_login_name')||'';currentUser=null;let input=document.getElementById('loginName');if(input&&userByName(saved))input.value=saved;document.getElementById('loginScreen').classList.remove('hidden');setTimeout(()=>{(input?.value?document.getElementById('loginPass'):input)?.focus?.()},180)}
function appLogin(){let rawName=document.getElementById('loginName').value||'',name=rawName.replace(/\s+/g,''),pass=(document.getElementById('loginPass').value||'').replace(/\D/g,''),u=userByName(name),err=document.getElementById('loginError');document.getElementById('loginName').value=name;if(!u){err.textContent='명단에 없는 이름입니다. 성명을 정확히 입력해 주세요.';return}let last4=(u.phone||'').replace(/\D/g,'').slice(-4);if(pass!==last4){err.textContent='휴대전화번호 끝 4자리가 맞지 않습니다.';return}currentUser=u;localStorage.setItem('cro_login_name',u.name);localStorage.setItem('loc_slot',u.slot);localStorage.setItem('loc_name',u.name);err.textContent='';appEnter()}
function appEnter(){document.body.classList.add('login-ready');document.getElementById('loginScreen').classList.add('hidden');let chip=document.getElementById('loginUserChip');chip.innerHTML=`👤 ${esc(currentUser.name)}<small>${userGroupText(currentUser)}</small>`;document.getElementById('accountName').textContent=currentUser.name;document.getElementById('accountMeta').textContent=`${userGroupText(currentUser)} · ${currentUser.org} · ${currentUser.title}`;let id=document.getElementById('locMyIdentity'),meta=document.getElementById('locMyIdentityMeta');if(id)id.textContent=`${currentUser.name} · ${userGroupText(currentUser)}`;if(meta)meta.textContent=`${currentUser.org} · ${currentUser.title} · 위치 DB 이름: ${currentUser.name}`;let admin=currentUser.name==='한상호';document.getElementById('attAdmin')?.classList.toggle('show',admin);locRefreshAll(false);attRefresh(false)}
async function appLogout(){try{if(localStorage.getItem('loc_sharing')==='1')await locStopSharing()}catch(e){}localStorage.removeItem('cro_login_name');currentUser=null;document.getElementById('accountPop').classList.remove('show');document.getElementById('loginPass').value='';document.getElementById('loginScreen').classList.remove('hidden')}
function toggleAccountPop(){document.getElementById('accountPop').classList.toggle('show')}
function ago(ts){if(!ts)return '-';let m=Math.floor((Date.now()-ts)/60000);if(m<1)return '방금';if(m<60)return `${m}분 전`;let h=Math.floor(m/60);if(h<24)return `${h}시간 ${m%60}분 전`;return `${Math.floor(h/24)}일 전`}
function lastSeenClock(ts){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Europe/Zagreb',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
const LOC_GROUP_COLORS={0:'#34495e',1:'#2274c9',2:'#26a269',3:'#e3912e',4:'#8a5bb7'};
function locGroupColor(g){return LOC_GROUP_COLORS[g]||'#607d8b'}
function locAgeInfo(ts){if(!ts)return {cls:'age-off',color:'#c6cdd1',label:'미공유'};let a=Date.now()-ts;if(a<=LIVE5)return {cls:'age-live',color:'#25a66a',label:'실시간'};if(a<=RECENT15)return {cls:'age-recent',color:'#2784c7',label:'5~15분'};if(a<=RECENT30)return {cls:'age-warn',color:'#e29a37',label:'15~30분'};if(a<=HOUR1)return {cls:'age-late',color:'#d85f52',label:'30~60분'};if(a<=HOUR3)return {cls:'age-1h',color:'#8156a5',label:'1~3시간'};return {cls:'age-old',color:'#8b969d',label:a<=HOUR6?'3~6시간':'6시간+'}}
function locCount(n){locBytes+=Math.max(0,n||0);let el=document.getElementById('locDataUsage');if(el)el.textContent=`이번 세션 위치 데이터 약 ${(locBytes/1024).toFixed(1)} KB · 실제 통신량은 HTTP/TLS 포함 시 더 큼`}
function updateLiveLocChip(){let el=document.getElementById('liveLoc');if(!el)return;let on=localStorage.getItem('loc_sharing')==='1',ts=locLastWrite||+(localStorage.getItem('loc_lastwrite')||0)||(currentUser&&locCache[currentUser.slot]?.ts)||0;el.classList.remove('transmitting','delayed');if(!on){el.textContent='📍 내 위치 OFF';return}if(ts&&Date.now()-ts<=LIVE5){el.classList.add('transmitting');el.textContent='📍 위치 전송중 · '+ago(ts)}else if(ts){el.classList.add('delayed');el.textContent='⚠ 위치공유 ON · '+ago(ts)}else{el.classList.add('delayed');el.textContent='⏳ 위치 전송 준비중'}}
async function token(){let tok=localStorage.getItem('fb_tok'),exp=+(localStorage.getItem('fb_exp')||0);if(tok&&Date.now()<exp)return tok;let rf=localStorage.getItem('fb_rf');if(rf){let b=new URLSearchParams({grant_type:'refresh_token',refresh_token:rf});let r=await fetch(`https://securetoken.googleapis.com/v1/token?key=${firebaseConfig.apiKey}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});let t=await r.text();locCount(b.toString().length+t.length);if(r.ok){let j=JSON.parse(t);localStorage.setItem('fb_tok',j.id_token);localStorage.setItem('fb_rf',j.refresh_token||rf);localStorage.setItem('fb_exp',Date.now()+3000000);return j.id_token}}let b=JSON.stringify({returnSecureToken:true});let r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${firebaseConfig.apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:b});let t=await r.text();locCount(b.length+t.length);if(!r.ok)throw Error('Firebase 익명 인증 실패');let j=JSON.parse(t);localStorage.setItem('fb_tok',j.idToken);localStorage.setItem('fb_rf',j.refreshToken);localStorage.setItem('fb_uid',j.localId);localStorage.setItem('fb_exp',Date.now()+3000000);return j.idToken}
function dbPath(slot=''){return `${firebaseConfig.databaseURL}/locations/${TRIP_CODE}${slot?'/'+slot:''}.json`}
function histPath(slot='',point=''){return `${firebaseConfig.databaseURL}/locationHistory/${TRIP_CODE}${slot?'/'+slot:''}${point?'/'+point:''}.json`}
function attCurrentPath(){return `${firebaseConfig.databaseURL}/attendanceCurrent/${TRIP_CODE}.json`}
function attPath(event='',slot=''){return `${firebaseConfig.databaseURL}/attendance/${TRIP_CODE}${event?'/'+event:''}${slot?'/'+slot:''}.json`}
function getPos(high=false){return new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(res,e=>rej(Error(e.code===1?'위치 권한을 허용해 주세요.':'위치 확인 실패')),{enableHighAccuracy:high,timeout:15000,maximumAge:high?0:60000}):rej(Error('위치 기능 미지원')))}
async function locRefreshAll(manual=false){if(!currentUser)return;try{let tk=await token(),r=await fetch(dbPath()+`?auth=${encodeURIComponent(tk)}`,{cache:'no-store'}),t=await r.text();locCount(t.length);if(!r.ok)throw Error('위치 DB 읽기 실패 — Rules 확인');let j=t&&t!=='null'?JSON.parse(t):{},now=Date.now();locCache={};Object.entries(j||{}).forEach(([k,v])=>{if(APP_BY_SLOT[k]&&v&&v.lat!=null&&now-(v.ts||0)<SHOWMAX)locCache[k]=v});localStorage.setItem('loc_read',Date.now());document.getElementById('locBackendState').textContent='Firebase 위치 연결 정상';document.getElementById('locBackendState').className='ok';renderRoster()}catch(e){document.getElementById('locBackendState').textContent=e.message||e;document.getElementById('locBackendState').className='note';if(manual)alert(e.message||e)}}
async function locWritePosition(p){if(!currentUser)throw Error('로그인이 필요합니다.');let tk=await token(),uid=localStorage.getItem('fb_uid')||'',data={uid,slot:currentUser.slot,group:currentUser.group,name:currentUser.name,lat:+p.coords.latitude.toFixed(5),lng:+p.coords.longitude.toFixed(5),accuracy:Math.round(p.coords.accuracy||0),ts:Date.now(),pageState:document.hidden?'background':'foreground'},b=JSON.stringify(data);let r=await fetch(dbPath(currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:b}),t=await r.text();locCount(b.length+t.length);if(!r.ok)throw Error('현재 위치 저장 실패 — Firebase Rules 확인');let historyOk=true;try{let hb=JSON.stringify(data),hr=await fetch(histPath(currentUser.slot,String(data.ts))+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:hb}),ht=await hr.text();locCount(hb.length+ht.length);if(!hr.ok)historyOk=false}catch(e){historyOk=false}locCache[currentUser.slot]=data;locLastPos=p;locLastWrite=data.ts;localStorage.setItem('loc_lastwrite',String(data.ts));let st=document.getElementById('locShareStatus');if(st)st.textContent=`전송중 · ${lastSeenClock(data.ts)} · 정확도 약 ${data.accuracy}m${historyOk?' · 이력 저장':' · 이력 저장 실패'}`;updateLiveLocChip();renderRoster();return true}
async function locUpdateNow(high=false){if(!currentUser)return;try{let p=await getPos(high);await locWritePosition(p)}catch(e){let st=document.getElementById('locShareStatus');if(st)st.textContent=e.message||e}}
function locStartTimer(){clearInterval(locTimer);locTimer=setInterval(()=>{if(localStorage.getItem('loc_sharing')==='1'&&!document.hidden)locUpdateNow(false)},300000)}
async function locStartSharing(){if(!currentUser){document.getElementById('loginScreen').classList.remove('hidden');return}localStorage.setItem('loc_sharing','1');localStorage.setItem('loc_slot',currentUser.slot);localStorage.setItem('loc_name',currentUser.name);await locUpdateNow(false);locStartTimer();updateLiveLocChip()}
async function locStopSharing(){clearInterval(locTimer);locTimer=null;localStorage.setItem('loc_sharing','0');if(currentUser){try{let tk=await token(),r=await fetch(dbPath(currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'DELETE'}),t=await r.text();locCount(t.length);delete locCache[currentUser.slot]}catch(e){}}let st=document.getElementById('locShareStatus');if(st)st.textContent='공유 OFF · 이동이력은 보존됨';updateLiveLocChip();renderRoster()}
function locUserMatchesFilter(u){return locFilter==='all'||(locFilter==='prof'&&u.group===0)||String(u.group)===locFilter}
function locSetFilter(f,btn){locFilter=f;document.querySelectorAll('#locFilters button').forEach(x=>x.classList.toggle('active',x===btn));renderRoster();updateMarkers()}
function renderRoster(){let box=document.getElementById('locRoster');if(!box)return;box.innerHTML='';let live=0,recent=0,old=0;APP_USERS.forEach(u=>{let r=locCache[u.slot];if(r&&Date.now()-r.ts<=LIVE5)live++;else if(r&&Date.now()-r.ts<=RECENT30)recent++;else old++});let groups=[1,2,3,4,0];groups.forEach(g=>{let members=APP_USERS.filter(u=>u.group===g&&locUserMatchesFilter(u));if(!members.length)return;let h=document.createElement('div');h.className='grouphead';h.innerHTML=`<span class="legend-ring" style="border-color:${locGroupColor(g)};vertical-align:-3px"></span> ${g===0?'교수님 · 인솔':g+'조 · '+members.length+'명'+(members.find(x=>x.leader)?' · 조장 '+members.find(x=>x.leader).name:'')}`;box.appendChild(h);members.forEach(u=>{let r=locCache[u.slot],ai=locAgeInfo(r?.ts),role=u.group===0?'교수님':(u.leader?'조장':'조원'),pos=r?`<span class="loc-age-badge">${ai.label}</span> · 마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)}) · ±${Math.round(r.accuracy||0)}m`:'위치 미공유';let row=document.createElement('div');row.className='person';row.innerHTML=`<span class="dot ${ai.cls}" style="box-shadow:0 0 0 4px ${locGroupColor(u.group)}"></span><div><div class="pname">${esc(u.name)}<small>${esc(u.org)} · ${esc(u.title)}</small></div><div class="pmeta">${u.group===0?'<span class="prof-badge">교수님</span>':`<span class="loc-role">${u.group}조 ${role}</span>`} · ${pos}</div></div><div class="loc-actions-mini"><button class="mini" onclick="locOpenPerson('${u.slot}')">상세</button><button class="mini" ${r?'':'disabled'} onclick="${r?`window.open('https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}','_blank')`:''}">지도</button></div>`;box.appendChild(row)})});document.getElementById('locLiveCount').textContent=live;document.getElementById('locStaleCount').textContent=recent;document.getElementById('locOffCount').textContent=old;let lr=localStorage.getItem('loc_read');document.getElementById('locLastRefresh').textContent=lr?new Date(+lr).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'-';updateLiveLocChip();updateMarkers()}
async function locOpenPerson(slot){let u=APP_BY_SLOT[slot],r=locCache[slot],box=document.getElementById('locPersonDetail');if(!u)return;let ai=locAgeInfo(r?.ts);box.classList.add('show');box.innerHTML=`<div class="loc-simple-head"><div><h3>${esc(u.name)} · ${userGroupText(u)}</h3><div class="small muted">${esc(u.org)} · ${esc(u.title)}</div></div><button onclick="document.getElementById('locPersonDetail').classList.remove('show')">닫기</button></div>${r?`<p><b>${ai.label}</b> · 마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)})<br>위치 ${r.lat.toFixed(5)}, ${r.lng.toFixed(5)} · 정확도 약 ${Math.round(r.accuracy||0)}m</p><div class="actions"><button onclick="window.open('https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}','_blank')">Google 지도</button><button class="primary" onclick="locLoadHistory('${slot}',true)">최근 이동기록</button></div>`:'<p class="muted">현재 공유된 위치가 없습니다.</p>'}<div id="locHistoryList" class="loc-history-list"></div>`;box.scrollIntoView({behavior:'smooth',block:'center'});if(r)locLoadHistory(slot,false)}
async function locLoadHistory(slot,draw=false){let list=document.getElementById('locHistoryList');if(list)list.innerHTML='<div class="small muted">최근 이동기록 불러오는 중…</div>';try{let tk=await token(),url=histPath(slot)+`?auth=${encodeURIComponent(tk)}&orderBy=%22%24key%22&limitToLast=96`,r=await fetch(url,{cache:'no-store'}),t=await r.text();locCount(t.length);if(!r.ok)throw Error('이동기록 읽기 실패');let j=t&&t!=='null'?JSON.parse(t):{},pts=Object.values(j||{}).filter(x=>x&&x.lat!=null).sort((a,b)=>a.ts-b.ts);if(list){let recent=pts.slice(-12).reverse();list.innerHTML=recent.length?recent.map(x=>`<div class="loc-history-row"><b>${lastSeenClock(x.ts)}</b><span>${x.lat.toFixed(5)}, ${x.lng.toFixed(5)} · ±${Math.round(x.accuracy||0)}m</span></div>`).join(''):'<div class="att-empty">저장된 이동기록이 없습니다.</div>'}if(draw&&pts.length){locToggleMap(true);setTimeout(()=>locDrawHistory(pts),450)}}catch(e){if(list)list.innerHTML=`<div class="att-empty">${esc(e.message||e)}</div>`}}
let locMapEngine='',googleOverlays=[],googleInfo=null,googleHistory=null,googleLoadStarted=false,googleLoadFailed=false;
function locToggleMap(force=false){let b=document.getElementById('locMap');if(!force&&b.classList.contains('show')){b.classList.remove('show');return}b.classList.add('show');locEnsureMap()}
function locSetEngineText(t){let e=document.getElementById('locMapEngine');if(e)e.textContent='지도 엔진: '+t}
function locEnsureMap(){if(locMapEngine==='google'&&window.google?.maps){initGoogleMap();return}if(locMapEngine==='leaflet'&&window.L){initLeafletMap();return}locLoadGoogleMap()}
function locLoadGoogleMap(){if(window.google?.maps){locMapEngine='google';initGoogleMap();return}if(googleLoadFailed){locLoadLeaflet();return}if(googleLoadStarted)return;googleLoadStarted=true;locSetEngineText('Google Maps 불러오는 중…');window.gm_authFailure=function(){googleLoadFailed=true;googleLoadStarted=false;locLoadLeaflet('Google Maps API 인증·도메인 제한·결제 설정을 확인하세요 · OpenStreetMap으로 전환')};window.__croGoogleMapReady=function(){if(googleLoadFailed)return;locMapEngine='google';locSetEngineText('Google Maps · 조색+시간색 이중표시');initGoogleMap()};let sc=document.createElement('script');sc.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(GOOGLE_MAPS_API_KEY)}&callback=__croGoogleMapReady&v=weekly&loading=async`;sc.async=true;sc.defer=true;sc.onerror=()=>{googleLoadFailed=true;googleLoadStarted=false;locLoadLeaflet('Google Maps 로드 실패 · OpenStreetMap 자동 전환')};document.head.appendChild(sc);setTimeout(()=>{if(!window.google?.maps&&locMapEngine!=='google'){googleLoadFailed=true;locLoadLeaflet('Google Maps 설정 미완료 · OpenStreetMap 자동 전환')}},6500)}
function initGoogleMap(){let box=document.getElementById('locMap');if(!box)return;if(locMapEngine!=='google')locMapEngine='google';if(!mapObj||!mapObj.getDiv){box.innerHTML='';mapObj=new google.maps.Map(box,{center:{lat:44.1,lng:16.2},zoom:6,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,gestureHandling:'greedy'});googleInfo=new google.maps.InfoWindow()}setTimeout(()=>google.maps.event.trigger(mapObj,'resize'),120);updateMarkers()}
function makeGoogleOverlay(u,r,ai){class M extends google.maps.OverlayView{onAdd(){let d=document.createElement('div');d.className='g-overlay';let group=u.group===0?'교수님':`${u.group}조`;d.innerHTML=`<div class="dual-marker" style="--group:${locGroupColor(u.group)};--age:${ai.color}"><span class="dual-label">${esc(u.name)} · ${ago(r.ts)}</span></div>`;d.onclick=()=>{googleInfo.setContent(`<div style="font-size:13px;line-height:1.65"><b>${esc(u.name)}</b> · ${group}<br><b>${ai.label}</b> · 마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)})<br>GPS 정확도 약 ${Math.round(r.accuracy||0)}m<br><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}">Google 지도에서 열기</a></div>`);googleInfo.setPosition({lat:r.lat,lng:r.lng});googleInfo.open(mapObj)};this.div=d;this.getPanes().overlayMouseTarget.appendChild(d)}draw(){let p=this.getProjection().fromLatLngToDivPixel(new google.maps.LatLng(r.lat,r.lng));if(this.div){this.div.style.left=p.x+'px';this.div.style.top=p.y+'px'}}onRemove(){this.div?.remove();this.div=null}}let ov=new M();ov.setMap(mapObj);return ov}
function updateMarkers(){if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv){googleOverlays.forEach(x=>x.setMap(null));googleOverlays=[];if(googleHistory){googleHistory.setMap(null);googleHistory=null}let bounds=new google.maps.LatLngBounds(),count=0;Object.entries(locCache).forEach(([slot,r])=>{let u=APP_BY_SLOT[slot];if(!u||!locUserMatchesFilter(u)||Date.now()-(r.ts||0)>SHOWMAX)return;let ai=locAgeInfo(r.ts);googleOverlays.push(makeGoogleOverlay(u,r,ai));bounds.extend({lat:r.lat,lng:r.lng});count++});if(count===1){mapObj.setCenter(bounds.getCenter());mapObj.setZoom(16)}else if(count>1)mapObj.fitBounds(bounds,55);return}updateLeafletMarkers()}
function locDrawHistory(pts){if(!pts.length)return;locToggleMap(true);if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv){if(googleHistory)googleHistory.setMap(null);googleHistory=new google.maps.Polyline({path:pts.map(x=>({lat:x.lat,lng:x.lng})),strokeColor:'#1f6f9c',strokeOpacity:.9,strokeWeight:4,map:mapObj});let b=new google.maps.LatLngBounds();pts.forEach(x=>b.extend({lat:x.lat,lng:x.lng}));mapObj.fitBounds(b,45);return}if(locMapEngine==='leaflet'&&window.L){if(historyLayer)mapObj.removeLayer(historyLayer);historyLayer=L.polyline(pts.map(x=>[x.lat,x.lng]),{weight:4,opacity:.8}).addTo(mapObj);mapObj.fitBounds(historyLayer.getBounds(),{padding:[40,40],maxZoom:17})}}
function locLoadLeaflet(msg='OpenStreetMap · 조색+시간색 이중표시'){locMapEngine='leaflet';locSetEngineText(msg);let box=document.getElementById('locMap');if(mapObj?.getDiv){mapObj=null;box.innerHTML=''}if(window.L){initLeafletMap();return}let c=document.createElement('link');c.rel='stylesheet';c.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(c);let sc=document.createElement('script');sc.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';sc.onload=initLeafletMap;sc.onerror=()=>box.innerHTML='<div style="padding:20px">지도를 불러오지 못했습니다. 사람별 ‘지도’ 버튼을 이용해 주세요.</div>';document.body.appendChild(sc)}
function initLeafletMap(){let box=document.getElementById('locMap');if(!window.L||!box)return;if(!mapObj||!mapObj.invalidateSize){box.innerHTML='';mapObj=L.map('locMap',{zoomControl:true}).setView([44.1,16.2],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapObj)}setTimeout(()=>mapObj.invalidateSize(),120);updateLeafletMarkers()}
function updateLeafletMarkers(){if(locMapEngine!=='leaflet'||!mapObj||!window.L)return;markers.forEach(m=>mapObj.removeLayer(m));markers=[];if(historyLayer){mapObj.removeLayer(historyLayer);historyLayer=null}let pts=[];Object.entries(locCache).forEach(([slot,r])=>{let u=APP_BY_SLOT[slot];if(!u||!locUserMatchesFilter(u)||Date.now()-(r.ts||0)>SHOWMAX)return;let ai=locAgeInfo(r.ts),group=u.group===0?'교수님':`${u.group}조`,html=`<div class="dual-marker" style="--group:${locGroupColor(u.group)};--age:${ai.color}"><span class="dual-label">${esc(u.name)} · ${ago(r.ts)}</span></div>`,icon=L.divIcon({className:'dual-leaf',html,iconSize:[22,22],iconAnchor:[11,11]});let m=L.marker([r.lat,r.lng],{icon}).addTo(mapObj).bindPopup(`<b>${esc(u.name)}</b><br>${group} · <b>${ai.label}</b><br>마지막 ${lastSeenClock(r.ts)} (${ago(r.ts)})<br>GPS 정확도 약 ${Math.round(r.accuracy||0)}m<br><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}">Google 지도에서 열기</a>`);markers.push(m);pts.push([r.lat,r.lng])});if(pts.length===1)mapObj.setView(pts[0],16);else if(pts.length>1)mapObj.fitBounds(pts,{padding:[55,55],maxZoom:17})}
function locFullScreenMap(){let b=document.getElementById('locMap');b.classList.add('show','fullscreen');document.body.classList.add('map-fullscreen');document.getElementById('locMapClose').classList.add('show');locEnsureMap();setTimeout(()=>{if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv)google.maps.event.trigger(mapObj,'resize');else if(mapObj?.invalidateSize)mapObj.invalidateSize()},150)}
function locExitFullScreenMap(){document.getElementById('locMap').classList.remove('fullscreen');document.body.classList.remove('map-fullscreen');document.getElementById('locMapClose').classList.remove('show');setTimeout(()=>{if(locMapEngine==='google'&&window.google?.maps&&mapObj?.getDiv)google.maps.event.trigger(mapObj,'resize');else if(mapObj?.invalidateSize)mapObj.invalidateSize()},150)}
async function locTestConnection(){try{await token();await locRefreshAll(true);alert('Firebase 인증과 위치 DB 조회가 정상입니다.')}catch(e){alert(e.message||e)}}
function locLifecycleSetup(){document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(localStorage.getItem('loc_sharing')==='1'&&Date.now()-locLastWrite>300000)locUpdateNow(false);locRefreshAll(false);attRefresh(false)}});window.addEventListener('online',()=>{locRefreshAll(false);attRefresh(false)});if(localStorage.getItem('loc_sharing')==='1')setTimeout(()=>{if(!document.hidden){locUpdateNow(false);locStartTimer()}},1200);pollTimer=setInterval(()=>{if(!document.hidden)locRefreshAll(false)},120000)}

// ----- 실시간 출석부 -----
function attUserMatchesFilter(u){return attFilter==='all'||(attFilter==='prof'&&u.group===0)||String(u.group)===attFilter}
function attSetFilter(f,btn){attFilter=f;document.querySelectorAll('#attFilters button').forEach(x=>x.classList.toggle('active',x===btn));attRender()}
async function attRefresh(manual=false){if(!currentUser)return;try{let tk=await token(),r=await fetch(attCurrentPath()+`?auth=${encodeURIComponent(tk)}`,{cache:'no-store'}),t=await r.text();locCount(t.length);attCurrent=t&&t!=='null'?JSON.parse(t):null;attChecks={};if(attCurrent?.id){let rr=await fetch(attPath(attCurrent.id)+`?auth=${encodeURIComponent(tk)}`,{cache:'no-store'}),tt=await rr.text();locCount(tt.length);if(rr.ok&&tt&&tt!=='null')attChecks=JSON.parse(tt)}attRender()}catch(e){if(manual)alert('출석부 조회 실패: '+(e.message||e))}}
function attRender(){let title=document.getElementById('attTitle'),meta=document.getElementById('attMeta'),roster=document.getElementById('attRoster'),btn=document.getElementById('attMyBtn');if(!title||!roster)return;if(!attCurrent){title.textContent='현재 진행 중인 출석이 없습니다.';meta.textContent='한상호가 출석을 시작하면 28명 전체가 실시간으로 확인할 수 있습니다.';document.getElementById('attCheckedCount').textContent='0';btn.disabled=true;btn.classList.remove('checked');btn.textContent='✓ 내 출석 확인';roster.innerHTML='<div class="att-empty">새 출석이 시작되면 28명의 확인 여부가 여기에 표시됩니다.</div>';return}title.textContent=attCurrent.title||attCurrent.type||'출석 확인';meta.textContent=`${lastSeenClock(attCurrent.createdAt)} 시작 · ${attCurrent.createdBy||''}`;let count=Object.values(attChecks||{}).filter(x=>x&&x.checked).length;document.getElementById('attCheckedCount').textContent=count;let mine=currentUser?attChecks[currentUser.slot]:null;btn.disabled=false;btn.classList.toggle('checked',!!mine?.checked);btn.textContent=mine?.checked?`✓ 확인완료 · ${new Date(mine.ts).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:'✓ 내 출석 확인';roster.innerHTML='';[1,2,3,4,0].forEach(g=>{let mem=APP_USERS.filter(u=>u.group===g&&attUserMatchesFilter(u));if(!mem.length)return;let h=document.createElement('div');h.className='grouphead';h.textContent=g===0?'교수님':`${g}조 · ${mem.length}명`;roster.appendChild(h);mem.forEach(u=>{let c=attChecks[u.slot],ok=!!c?.checked,row=document.createElement('div');row.className='att-row';row.innerHTML=`<span class="att-state ${ok?'ok':''}"></span><div class="att-name">${esc(u.name)}<small>${esc(u.org)} · ${u.group===0?'교수님':(u.leader?'조장':'조원')}</small></div><div class="att-status ${ok?'checked':''}">${ok?`확인 · ${new Date(c.ts).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:'미확인'}</div>`;roster.appendChild(row)})})}
async function attToggleSelf(){if(!currentUser||!attCurrent?.id)return;try{let tk=await token(),existing=attChecks[currentUser.slot];if(existing?.checked){let r=await fetch(attPath(attCurrent.id,currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'DELETE'}),t=await r.text();locCount(t.length);if(!r.ok)throw Error('출석 취소 실패');delete attChecks[currentUser.slot]}else{let d={uid:localStorage.getItem('fb_uid')||'',slot:currentUser.slot,name:currentUser.name,group:currentUser.group,checked:true,ts:Date.now()},b=JSON.stringify(d),r=await fetch(attPath(attCurrent.id,currentUser.slot)+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:b}),t=await r.text();locCount(b.length+t.length);if(!r.ok)throw Error('출석 저장 실패 — Firebase Rules 확인');attChecks[currentUser.slot]=d}attRender()}catch(e){alert(e.message||e)}}
async function attCreateEvent(){if(!currentUser||currentUser.name!=='한상호'){alert('출석 시작은 한상호만 사용할 수 있습니다.');return}let type=document.getElementById('attType').value,custom=document.getElementById('attCustomTitle').value.trim(),now=Date.now(),d={id:String(now),type,title:custom||type,createdBy:currentUser.name,createdAt:now},b=JSON.stringify(d);try{let tk=await token(),r=await fetch(attCurrentPath()+`?auth=${encodeURIComponent(tk)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:b}),t=await r.text();locCount(b.length+t.length);if(!r.ok)throw Error('출석 시작 실패 — Firebase Rules 확인');attCurrent=d;attChecks={};document.getElementById('attCustomTitle').value='';attRender()}catch(e){alert(e.message||e)}}
async function attResetCurrent(){if(!currentUser||currentUser.name!=='한상호'){alert('출석 리셋은 한상호만 사용할 수 있습니다.');return}if(!attCurrent){alert('현재 진행 중인 출석이 없습니다.');return}if(!confirm('현재 진행 중인 출석을 리셋할까요?\n이전 출석 이력은 Firebase에 그대로 남습니다.'))return;try{let tk=await token(),r=await fetch(attCurrentPath()+`?auth=${encodeURIComponent(tk)}`,{method:'DELETE'}),t=await r.text();locCount(t.length);if(!r.ok)throw Error('출석 리셋 실패 — Firebase Rules 확인');attCurrent=null;attChecks={};attRender()}catch(e){alert(e.message||e)}}

function attStartPolling(){clearInterval(attTimer);attTimer=setInterval(()=>{if(!document.hidden&&currentUser)attRefresh(false)},20000)}

document.getElementById('loginName')?.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('loginPass')?.focus()});document.getElementById('loginPass')?.addEventListener('keydown',e=>{if(e.key==='Enter')appLogin()});
appInitLogin();locLifecycleSetup();attStartPolling();updateLiveLocChip();setInterval(()=>{updateLiveLocChip();if(!document.hidden){renderRoster();attRender()}},60000);

function filterTeamRoster(q){q=String(q||'').trim().toLowerCase();document.querySelectorAll('#teamAllRoster .team-member').forEach(el=>{let hay=(el.dataset.name+' '+el.dataset.org+' '+el.textContent).toLowerCase();el.style.display=!q||hay.includes(q)?'grid':'none'})}
// checklist

let cw=document.getElementById('checks');
CHECK_GROUPS.forEach((g,gi)=>{let sec=document.createElement('div');sec.className='check-group';sec.innerHTML=`<h3>${g.title}</h3><div class="check-cat-desc">${g.desc}</div>`;g.items.forEach((it,ii)=>{let k=`chk2_${gi}_${ii}`,d=document.createElement('div');d.className='card check';d.dataset.type=it[1];d.innerHTML=`<input type="checkbox" id="${k}"><label for="${k}">${it[0]}<small>${it[1]}</small></label>`;sec.appendChild(d);let cb=d.querySelector('input');cb.checked=localStorage.getItem(k)==='1';cb.onchange=()=>{localStorage.setItem(k,cb.checked?'1':'0');prog()}});cw.appendChild(sec)});
function prog(){let a=[...document.querySelectorAll('.check input')],n=a.filter(x=>x.checked).length;document.getElementById('prog').style.width=(a.length?n/a.length*100:0)+'%';document.getElementById('progText').textContent=`${n} / ${a.length} 완료 · 이 휴대폰에 자동저장`}
function checkAll(v){document.querySelectorAll('.check input').forEach(cb=>{cb.checked=v;localStorage.setItem(cb.id,v?'1':'0')});prog()}
function checkEssential(){document.querySelectorAll('.check').forEach(el=>{let t=el.dataset.type;el.style.display=(t==='필수'||t==='이번여행'||t==='날씨')?'flex':'none'});let tools=document.querySelector('#check .check-tools');if(tools&&!document.getElementById('checkShowAll')){let b=document.createElement('button');b.id='checkShowAll';b.textContent='전체 항목 다시 보기';b.className='btn';b.onclick=()=>{document.querySelectorAll('.check').forEach(x=>x.style.display='flex');b.remove()};tools.appendChild(b)}}
prog();
