/* MIX43: consistent daily route maps without Google Maps JS dependency. */
(function(){
  'use strict';
  const P=window.CRO_ROUTE_POINTS||{};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function stateEl(i){return document.getElementById('scheduleRouteState-'+i)}function mapEl(i){return document.getElementById('scheduleRouteMap-'+i)}function setState(i,msg){const e=stateEl(i);if(e)e.textContent=msg||''}
  function panelMarkup(d,i){const pts=P[d.date]||[],stops=pts.map((p,n)=>`<span class="journey-stop"><i>${n+1}</i><span>${esc(p.n)}</span></span>`).join(''),mapAction=d.map?`<a class="primary" href="${esc(d.map)}" target="_blank" rel="noopener">Google 지도에서 전체 동선</a>`:'';return `<section class="schedule-route-panel" data-route-date="${esc(d.date)}" aria-label="${esc(d.date)} 이동동선"><div class="journey-heading"><div><small>${esc(d.date.slice(5).replace('-','/'))} · ROUTE</small><b>${esc(d.title)}</b></div><span class="map-badge">동선지도</span></div><div class="schedule-route-map-wrap"><div id="scheduleRouteMap-${i}" class="schedule-route-map" aria-label="${esc(d.title)} 지도"></div><div id="scheduleRouteState-${i}" class="schedule-route-state">동선 지도를 준비합니다.</div></div><div class="journey-stops">${stops}</div><div class="schedule-route-actions">${mapAction}</div></section>`}
  function mount(){[...document.querySelectorAll('#dayPanels .panel')].forEach((panel,i)=>{if(panel.querySelector('.schedule-route-panel')||!days?.[i])return;const summary=panel.querySelector('.day-summary'),host=document.createElement('div');host.innerHTML=panelMarkup(days[i],i);const route=host.firstElementChild;if(summary)summary.insertAdjacentElement('afterend',route);else panel.prepend(route)})}
  function render(i){const d=days?.[i],box=mapEl(i);if(!d||!box||!window.GSPA_RouteMap)return;const pts=P[d.date]||[];setState(i,navigator.onLine===false?'오프라인 동선도':'동선 지도를 불러오는 중…');window.GSPA_RouteMap.render(box,pts,{label:d.title}).then(ok=>setState(i,ok?'OpenStreetMap · 번호 순서':'오프라인 동선도 · 아래 Google 지도 버튼 사용')).catch(()=>setState(i,'오프라인 동선도 · 아래 Google 지도 버튼 사용'))}
  function activeIndex(){return[...document.querySelectorAll('#dayPanels .panel')].findIndex(p=>p.classList.contains('active'))}function scheduleVisible(){return document.getElementById('schedule')?.classList.contains('app-view-active')||location.hash==='#schedule'}function ensureActive(){if(scheduleVisible())setTimeout(()=>render(activeIndex()),70)}
  function bind(){document.getElementById('dayTabs')?.addEventListener('click',()=>setTimeout(ensureActive,90));window.addEventListener('cro-route',e=>{if(e.detail?.view==='schedule')ensureActive()});window.addEventListener('online',ensureActive);window.addEventListener('resize',()=>{const i=activeIndex();if(i>=0)window.GSPA_RouteMap?.invalidate(mapEl(i))},{passive:true})}
  function init(){mount();bind();ensureActive()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
