/* MIX74 - shared Croatia rainbow T-shirt selection. Read for all logged-in Croatia users, write controls for each group leader only. */
(function(){
  'use strict';
  if((window.GSPA_TRIP_ID||'croatia')!=='croatia')return;
  const DATA=window.CRO_SHIRT_DATA;
  if(!DATA||!Array.isArray(DATA.participants))return;
  const EVENT='shirtSelection2026';
  const PATH='attendance/'+TRIP_CODE+'/'+EVENT;
  const CACHE='cro.shirts.shared.v1';
  const groupColors={1:'#287fc4',2:'#2e9a69',3:'#dd872f',4:'#8056a5'};
  const byMember=new Map(DATA.participants.map(p=>[p.memberId,p]));
  const byName=new Map(DATA.participants.map(p=>[p.name,p]));
  let shared={};
  let viewType='group',currentGroup=1,currentColor=null,busy=false,poll=null,lastSync=0;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function safeRead(){try{return JSON.parse(localStorage.getItem(CACHE)||'{}')||{}}catch(_){return {}}}
  function saveCache(){try{localStorage.setItem(CACHE,JSON.stringify(shared))}catch(_){}}
  function normalizeServer(raw){const out={};if(raw&&typeof raw==='object'){for(const r of Object.values(raw)){if(!r||typeof r!=='object'||r.group<1||r.group>4||r.shirtVersion!==1)continue;const g=+r.group;if(!out[g]||+(r.ts||0)>+(out[g].ts||0))out[g]=r;}}return out;}
  function groupState(g){const s=shared&&shared[g];return s&&typeof s==='object'?s:null}
  function isFinal(g){return groupState(g)?.status==='final'&&groupState(g)?.assignments}
  function isSelected(g){const s=groupState(g);return !!(s?.assignments&&(s.status==='selected'||s.status==='final'))}
  function finalizedCount(){return [1,2,3,4].filter(isFinal).length}
  function leaderOf(g){return DATA.leaders?.[g]||DATA.leaders?.[String(g)]||DATA.participants.find(p=>p.group===g&&p.leader)?.name||''}
  function myLeaderGroup(){if(typeof currentUser==='undefined'||!currentUser)return 0;const p=byName.get(currentUser.name);return p?.leader?p.group:0}
  function canEdit(g){return myLeaderGroup()===+g&&currentUser?.name===leaderOf(+g)}
  function groupPeople(g){return DATA.participants.filter(p=>p.group===+g)}
  function color(name){return DATA.colors.find(c=>c.name===name)||{name:'흰색',hex:'#ffffff'};}
  function fmt(ts,zone){if(!ts)return '';try{return new Intl.DateTimeFormat('ko-KR',{timeZone:zone,month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ts))}catch(_){return ''}}
  function finalStamp(s){if(!s?.finalizedAt)return '';const cro=fmt(s.finalizedAt,'Europe/Zagreb'),kor=fmt(s.finalizedAt,'Asia/Seoul');return `최종 ${cro} 크로아티아 · ${kor} 한국`;}
  function groupStatusHtml(g){const s=groupState(g),done=isFinal(g);let text='미선정';if(s?.status==='selected')text='선택 · 미확정';if(done)text=finalStamp(s)||'확정';return `<div class="shirt-group-status ${done?'done':''}" style="border-left:4px solid ${groupColors[g]}"><b>${g}조 · ${done?'확정':s?.status==='selected'?'선택':'미완료'}</b><span>${esc(text)}</span></div>`;}
  function assignmentFor(p){return groupState(p.group)?.assignments?.[p.memberId]||null}
  function card(p,showGroup=false){const assigned=assignmentFor(p),c=color(assigned);return `<article class="shirt-person ${p.leader?'is-leader':''}" data-shirt-member="${esc(p.memberId)}">${p.leader?'<span class="shirt-role-badge leader">조장</span>':''}${p.professor?'<span class="shirt-role-badge prof">교수</span>':''}<div class="shirt-character"><img class="shirt-head" src="${esc(p.photo)}" alt="${esc(p.name)}"><div class="shirt-neck"></div><div class="shirt-torso" style="background:${c.hex}"></div><img class="shirt-jeans" src="${esc(DATA.jeans)}" alt=""></div><div class="shirt-podium"><div class="shirt-name">${esc(p.name)}</div><div class="shirt-group-line">${p.group}조${p.leader?' · 조장':''}${p.professor?' · 교수':''}</div><div class="shirt-color-line"><span class="shirt-color-dot" style="background:${c.hex}"></span>${esc(assigned||'흰색')}</div></div></article>`;}
  function stateText(g){const s=groupState(g);if(isFinal(g))return `<span>✓ 확정</span><small>${esc(finalStamp(s))}<br>${esc(s.finalizedByName||leaderOf(g))}</small>`;if(s?.status==='selected')return '<span>선택됨 · 미확정</span><small>조장 확정 대기</small>';return '<span>미선정</span><small>조장 옷 선택 대기</small>';}
  function roleNote(g){const mine=canEdit(g),leader=leaderOf(g);if(mine)return `<div class="shirt-role-note leader"><b>${esc(leader)} 조장 권한</b> · ${g}조 옷 선택·확정·리셋을 할 수 있습니다. 다른 조 결과는 조회만 가능합니다.</div>`;return `<div class="shirt-role-note"><b>전체 조회</b> · 모든 접속자는 1~4조 배정과 확정 상태를 볼 수 있습니다. ${g}조 변경은 <b>${esc(leader)} 조장</b>만 가능합니다.</div>`;}
  function syncMenu(){const btn=document.getElementById('shirtMenuBtn');if(!btn)return;const n=finalizedCount();btn.classList.toggle('shirt-menu-complete',n===4);const sm=btn.querySelector('small');if(sm)sm.innerHTML=`티셔츠 · <em class="shirt-menu-badge">${n}/4</em>`;}
  function render(){const app=document.getElementById('shirtApp');if(!app)return;const n=finalizedCount();let head=`<section class="shirt-progress-card"><div class="shirt-progress-top"><div><small>전체 진행 현황</small><strong>${n===4?'4개 조 최종 확정':'조별 최종 선택 진행 중'}</strong></div><div class="shirt-progress-count">${n}/4</div></div><div class="shirt-group-statuses">${[1,2,3,4].map(groupStatusHtml).join('')}</div></section>`;
    const selectors=`<section class="shirt-view-card"><div class="shirt-selector-label">조별 조회</div><div class="shirt-group-buttons">${[1,2,3,4].map(g=>`<button type="button" class="shirt-view-btn shirt-group-btn ${viewType==='group'&&currentGroup===g?'active':''}" data-shirt-group="${g}">${g}조</button>`).join('')}</div><div class="shirt-selector-label">색깔별 조회</div><div class="shirt-color-buttons">${DATA.colors.map(c=>`<button type="button" class="shirt-view-btn shirt-color-btn ${viewType==='color'&&currentColor===c.name?'active':''}" data-shirt-color="${esc(c.name)}"><span class="shirt-swatch" style="background:${c.hex}"></span>${esc(c.name)}</button>`).join('')}</div></section>`;
    let panel='';
    if(viewType==='group'){
      const g=currentGroup,s=groupState(g),mine=canEdit(g),selected=isSelected(g),final=isFinal(g);
      panel=`<section class="shirt-panel"><div class="shirt-panel-head"><h3>${g}조 티셔츠</h3><div class="shirt-state">${stateText(g)}</div></div>${roleNote(g)}<div class="shirt-actions">${mine?`<button class="shirt-action draw" type="button" data-shirt-action="draw" ${busy||final?'disabled':''}>🎲 옷 선택</button><button class="shirt-action confirm" type="button" data-shirt-action="confirm" ${busy||!selected||final?'disabled':''}>✓ 최종 확정</button><button class="shirt-action reset" type="button" data-shirt-action="reset" ${busy||(!selected&&!final)?'disabled':''}>↺ 리셋</button>`:''}<button class="shirt-action image" type="button" data-shirt-action="image" ${n<4?'disabled':''}>▣ 최종명단 이미지</button></div><div class="shirt-people">${groupPeople(g).map(p=>card(p)).join('')}</div><div class="shirt-final-foot"><b>${esc(leaderOf(g))} 조장</b><span>${final?'확정 후 모든 사용자 동시 조회':'확정 전에도 선택 결과는 공유 조회'}</span></div></section>`;
    }else{
      const matches=DATA.participants.filter(p=>assignmentFor(p)===currentColor),c=color(currentColor);
      panel=`<section class="shirt-panel"><div class="shirt-panel-head"><h3><span class="shirt-color-dot" style="background:${c.hex};width:13px;height:13px"></span>${esc(currentColor)} 티셔츠</h3><div class="shirt-state"><span>${matches.length}명</span><small>전체 조 통합 조회</small></div></div><div class="shirt-people">${matches.length?matches.map(p=>card(p,true)).join(''):`<div class="shirt-empty">${esc(currentColor)} 티셔츠가 아직 배정되지 않았습니다.</div>`}</div></section>`;
    }
    app.innerHTML=`<div class="shirt-shell">${head}${selectors}${panel}<div id="shirtSync" class="shirt-sync ${lastSync?'ok':''}">${lastSync?'공유결과 동기화 · '+fmt(lastSync,'Asia/Seoul')+' 한국':'공유결과 확인 대기'}</div></div>`;syncMenu();applyPersonalTheme();
  }
  function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const ar=new Uint32Array(1);if(crypto?.getRandomValues)crypto.getRandomValues(ar);const r=crypto?.getRandomValues?ar[0]/4294967296:Math.random(),j=Math.floor(r*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  async function putGroup(g,record){if(!canEdit(g))throw Error('해당 조의 조장만 변경할 수 있습니다.');if(!navigator.onLine)throw Error('공유 저장은 인터넷 연결이 필요합니다.');if(typeof window.token==='function')await window.token();const uid=localStorage.getItem('fb_uid')||'';if(!uid)throw Error('공유 인증 정보를 확인할 수 없습니다.');const slotKey=('shirt_g'+g+'_'+uid.replace(/[^A-Za-z0-9_-]/g,'').slice(0,48));record={uid,slot:slotKey,name:currentUser.name,group:+g,checked:true,ts:{'.sv':'timestamp'},shirtVersion:1,leader:leaderOf(g),updatedByName:currentUser.name,...record};const res=await Integration.api(PATH+'/'+slotKey,{method:'PUT',body:JSON.stringify(record)});return res.data;}
  async function refresh(force=false){if((window.GSPA_TRIP_ID||'croatia')!=='croatia')return;if(!force&&Date.now()-lastSync<4000)return;try{const res=await Integration.api(PATH);shared=normalizeServer(res.data);lastSync=Date.now();saveCache();render()}catch(e){const el=document.getElementById('shirtSync');if(el){el.className='shirt-sync error';el.textContent='공유결과 연결 실패 · 저장된 결과 표시';}applyPersonalTheme();}}
  async function drawGroup(g){if(busy||!canEdit(g)||isFinal(g))return;busy=true;render();try{await refresh(true);if(isFinal(g))throw Error('이미 최종 확정된 조입니다. 리셋 후 다시 선택해 주세요.');const colors=shuffle(DATA.colors.map(c=>c.name)),assign={};groupPeople(g).forEach((p,i)=>assign[p.memberId]=colors[i]);shared[g]=await putGroup(g,{status:'selected',assignments:assign});lastSync=Date.now();saveCache();render();for(const p of groupPeople(g)){const el=document.querySelector(`[data-shirt-member="${p.memberId}"]`);el?.classList.add('is-winner');await new Promise(r=>setTimeout(r,120));}toast(`${g}조 티셔츠 선택이 공유되었습니다.`)}catch(e){toast(e.message||'저장에 실패했습니다.',true)}finally{busy=false;await refresh(true);render()}}
  async function confirmGroup(g){if(busy||!canEdit(g)||!isSelected(g)||isFinal(g))return;if(!confirm(`${g}조 배정을 최종 확정할까요? 확정일자가 모든 사용자에게 표시됩니다.`))return;busy=true;render();try{await refresh(true);if(isFinal(g))throw Error('이미 최종 확정되었습니다.');if(!isSelected(g))throw Error('선택 결과가 없습니다.');const assignments={...groupState(g).assignments};shared[g]=await putGroup(g,{status:'final',assignments,finalizedByName:currentUser.name,finalizedAt:{'.sv':'timestamp'}});lastSync=Date.now();saveCache();render();toast(`${g}조 최종 확정 완료`)}catch(e){toast(e.message||'확정에 실패했습니다.',true)}finally{busy=false;await refresh(true);render()}}
  async function resetGroup(g){if(busy||!canEdit(g)||!groupState(g))return;if(!confirm(`${g}조 티셔츠 선택과 확정 상태를 초기화할까요?`))return;busy=true;render();try{shared[g]=await putGroup(g,{status:'reset'});lastSync=Date.now();saveCache();render();toast(`${g}조 결과가 초기화되었습니다.`)}catch(e){toast(e.message||'초기화에 실패했습니다.',true)}finally{busy=false;await refresh(true);render()}}
  function toast(text,error=false){if(typeof window.appActionToast==='function'){window.appActionToast(text,error?'error':'success');return}const el=document.getElementById('appActionToast');if(el){el.textContent=text;el.className='app-action-toast show';setTimeout(()=>el.classList.remove('show'),2600)}else alert(text)}
  function hexSoft(hex,a=.13){const h=hex.replace('#',''),n=parseInt(h,16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`}
  function themeUser(){let u=(typeof currentUser!=='undefined'&&currentUser)||null;if(!u){try{const typed=String(document.getElementById('loginName')?.value||'').normalize('NFC').replace(/[\s\u200B-\u200D\uFEFF]+/g,'');const n=typed||localStorage.getItem('cro_login_name')||'';u=n?{name:n,memberId:TEAM_MEMBERS.find(x=>x.name===n)?.memberId}:null}catch(_){}}return u}
  function applyPersonalTheme(){const u=themeUser();let p=u&&(byMember.get(u.memberId)||byName.get(u.name));let assigned=p&&isFinal(p.group)?assignmentFor(p):null;if(!assigned){document.body.classList.remove('shirt-theme-active','shirt-all-final');['--shirt-accent','--shirt-accent-soft','--shirt-accent-text'].forEach(k=>document.body.style.removeProperty(k));return;}const c=color(assigned),dark=['노랑'].includes(c.name);document.body.classList.add('shirt-theme-active');document.body.classList.toggle('shirt-all-final',finalizedCount()===4);document.body.style.setProperty('--shirt-accent',c.hex);document.body.style.setProperty('--shirt-accent-soft',hexSoft(c.hex,.14));document.body.style.setProperty('--shirt-accent-text',dark?'#3d3300':'#fff');document.body.dataset.shirtColor=c.name;}
  async function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
  async function exportImage(){if(finalizedCount()<4)return;try{toast('최종명단 이미지 만드는 중…');const W=1600,H=2150,c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle='#f5f8fb';x.fillRect(0,0,W,H);x.fillStyle='#075f8b';x.fillRect(0,0,W,150);x.fillStyle='white';x.font='bold 56px sans-serif';x.fillText('크로아티아 무지개 티셔츠 최종 배정',70,92);x.font='28px sans-serif';x.fillText('서울대학교 행정대학원 공공리더십과정 17기',72,132);const jeans=await loadImage(DATA.jeans),imgs={};for(const p of DATA.participants)imgs[p.memberId]=await loadImage(p.photo);const gx=70,cardW=1460,cardH=440,gap=28;for(let g=1;g<=4;g++){const y=190+(g-1)*(cardH+gap);x.fillStyle='white';x.strokeStyle=groupColors[g];x.lineWidth=5;x.beginPath();x.roundRect(gx,y,cardW,cardH,28);x.fill();x.stroke();x.fillStyle=groupColors[g];x.font='bold 44px sans-serif';x.fillText(g+'조',gx+28,y+55);const members=groupPeople(g);for(let i=0;i<7;i++){const p=members[i],px=gx+24+i*202,base=y+355,cc=color(assignmentFor(p)),head=imgs[p.memberId];x.drawImage(head,px+50,y+75,100,112);x.fillStyle='#efc0a4';x.fillRect(px+91,y+175,18,18);x.fillStyle=cc.hex;x.strokeStyle='#cfd8de';x.lineWidth=2;x.beginPath();x.roundRect(px+54,y+188,92,70,20);x.fill();x.stroke();x.drawImage(jeans,px+68,y+245,64,92);x.fillStyle='#eef3f6';x.strokeStyle='#aebfc8';x.beginPath();x.roundRect(px+24,base-8,152,82,12);x.fill();x.stroke();x.fillStyle='#173d50';x.textAlign='center';x.font='bold 24px sans-serif';x.fillText(p.name,px+100,base+18);x.fillStyle='#56717f';x.font='bold 16px sans-serif';x.fillText(g+'조'+(p.leader?' · 조장':'')+(p.professor?' · 교수':''),px+100,base+42);x.fillStyle=cc.hex;x.beginPath();x.arc(px+72,base+59,8,0,Math.PI*2);x.fill();x.fillStyle='#657780';x.font='16px sans-serif';x.fillText(assignmentFor(p)||'흰색',px+110,base+64)}}x.textAlign='left';x.fillStyle='#71818b';x.font='22px sans-serif';x.fillText('조별 빨·주·노·초·파·남·보 각 1명 · 4개 조 최종 확정',72,2100);const a=document.createElement('a');a.download='크로아티아_티셔츠_최종명단.png';a.href=c.toDataURL('image/png');a.click();toast('최종명단 이미지를 만들었습니다.')}catch(e){toast('이미지 생성에 실패했습니다.',true)}}
  function bind(){document.addEventListener('input',e=>{if(e.target?.id==='loginName')applyPersonalTheme()});document.addEventListener('click',e=>{const g=e.target.closest('[data-shirt-group]');if(g){currentGroup=+g.dataset.shirtGroup;viewType='group';currentColor=null;render();return}const c=e.target.closest('[data-shirt-color]');if(c){viewType='color';currentColor=c.dataset.shirtColor;render();return}const a=e.target.closest('[data-shirt-action]');if(!a)return;const action=a.dataset.shirtAction;if(action==='draw')drawGroup(currentGroup);if(action==='confirm')confirmGroup(currentGroup);if(action==='reset')resetGroup(currentGroup);if(action==='image')exportImage();});window.addEventListener('cro-auth-change',()=>{if(typeof currentUser!=='undefined'&&currentUser){const me=byMember.get(currentUser.memberId)||byName.get(currentUser.name);if(me){currentGroup=me.group;viewType='group';currentColor=null;}}applyPersonalTheme();render();if(typeof currentUser!=='undefined'&&currentUser)refresh(true)});window.addEventListener('cro-route',e=>{if(e.detail?.view==='shirts')refresh(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&typeof currentUser!=='undefined'&&currentUser)refresh(false)})}
  function init(){shared=safeRead();render();bind();applyPersonalTheme();refresh(true);poll=setInterval(()=>{if(document.hidden)return;if(typeof currentUser!=='undefined'&&currentUser)refresh(false)},8000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.CRO_Shirts={refresh,render,applyPersonalTheme};
})();
